influxdata/kapacitor

integrations/streamer_test.go
pipeline/alert.go

fix history type

---

build.py

compute md5sums when building packages

---

cmd/kapacitor/main.go

use env var for kapacitor url

---

CHANGELOG.md

Fixes #100
We will keep the CHANGELOG up-to-date now. I back-filled the last few minor releases.

backfill change log, will keep up-to-date now

---

CHANGELOG.md
batch.go

fix race with timeTicker

---

CHANGELOG.md
group_by.go
integrations/streamer_test.go
pipeline/stream.go
stream.go
where.go

Fixes #122
Add groupBy property to stream node to optimize where + … groupBy conditions.
I added the groupBy functionality directly to the stream node so that order will not effect performance and avoid future errors. 
I also just fixed the nil map issue.

Fix nil map in WhereNode

---

CHANGELOG.md
alert.go
services/smtp/service.go
task_master.go

Fix smtp not sending emails when using to list from config

---

cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go

Fix error on early 404

---

cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/replay/service.go

Fix hang in DoStreamRecordReplay
Simplify httpGetRetry logic.

Fix some test issues

---

CHANGELOG.md
cmd/kapacitord/run/server.go
services/httpd/handler.go
udf_process_test.go

update metastore to metaclient, fix flaky test

---

CHANGELOG.md
build.py

compress tarbals from build

---

alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/sensu/config.go
services/sensu/service.go
task_master.go

Sensu integration for Kapacitor

---

CHANGELOG.md
batch.go
pipeline/batch.go

fix show command for dot output with batch tasks

---

.gitignore
CHANGELOG.md
cmd/kapacitord/run/server_test.go
etc/kapacitor/kapacitor.conf
task_master.go
udf/agent/agent.go
udf/agent/examples/moving_avg/README.md
udf/agent/examples/moving_avg/moving_avg.go
udf/agent/examples/moving_avg/moving_avg.py
udf/agent/examples/outliers/README.md
udf/agent/examples/outliers/outliers.go
udf/agent/examples/outliers/outliers.py
udf/agent/py/agent.py
udf/agent/py/udf_pb2.py
udf/udf.pb.go
udf/udf.proto
udf_process.go

Fixes some bugs and adds tests around UDFs and batches.
Makes working with Groups and UDFs simpler.

Make UDFs and groups play nice

---

CHANGELOG.md
cmd/kapacitor/main.go

fix panic with define command and invalid dbrp value

---

pipeline/node.go

Fixed typo in MapReduce documentation

---

CHANGELOG.md
integrations/streamer_test.go
pipeline/stream.go
pipeline/where.go
services/slack/service.go
where.go

Fix issues with where node

---

services/alerta/service.go
services/hipchat/service.go
services/opsgenie/service.go
services/pagerduty/service.go
services/sensu/service.go
services/slack/service.go
services/victorops/service.go

This will help to figure out what is going on with #189

Better error messages from external alerting services

---

CHANGELOG.md
batch.go
cmd/kapacitor/main.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/task_store/service.go
task.go

fix hang when deleteing invalid batch task

---

CHANGELOG.md
services/influxdb/config.go
services/influxdb/service.go

Fixes #187 
There still may be an issue with failing to create subscriptions but this should make the problem easier to track.

Retry connecting to InfluxDB on startup

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
services/alerta/service.go
task_master.go

fix various usability issues with Alerta integration

---

CHANGELOG.md
group_by.go
integrations/data/TestStream_BatchGroupBy.srpl
integrations/helpers_test.go
integrations/streamer_test.go
models/batch.go

implement batch group by

---

CHANGELOG.md
services/alerta/service.go
services/deadman/config.go
services/hipchat/service.go
services/opsgenie/service.go
services/pagerduty/service.go
services/sensu/service.go
services/slack/service.go
services/talk/service.go
services/victorops/service.go

better error messages for alert handlers

---

CHANGELOG.md
cmd/kapacitord/run/server_test.go
pipeline/pipeline.go
pipeline/pipeline_test.go
pipeline/stream.go
stream.go
task.go

Add source stream node

---

CHANGELOG.md
services/httpd/handler.go
services/task_store/service.go

add OPTIONS method for task delete

---

CHANGELOG.md
cmd/kapacitord/run/server_test.go
expvar/expvar.go
global_stats.go
integrations/data/TestStream_JoinOn.srpl
integrations/streamer_test.go
join.go
models/batch.go
models/point.go
node.go
pipeline/join.go
services/reporting/service.go
timer/timer.go
timer/timer_test.go
union.go

Fixes #144 as explained in the issue.

Implement join.On functionality

---

CHANGELOG.md
cmd/kapacitord/run/server.go
services/influxdb/service.go
services/udp/service.go

update udp stats, and use clusterID for subscription names

---

influxdb_out.go

Fixes #269 Turns out it was in InfluxDBOut not Join ;)

Fix hang in influxdb_out

---

CHANGELOG.md
services/httpd/service.go

Graceful stop of httpd service

---

derivative.go

Fix bad timing logic in derivative

---

cmd/kapacitord/run/server.go

http starts up last so requests cant be made before we are ready

---

alert.go
udf/udf.pb.go
vendor/github.com/influxdb/influxdb/cluster/internal/data.pb.go
vendor/github.com/influxdb/influxdb/services/copier/internal/internal.pb.go
vendor/github.com/influxdb/influxdb/services/meta/internal/meta.pb.go
vendor/github.com/influxdb/influxdb/tsdb/legacy_internal/meta.pb.go

Fix filepath issue

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go

Add .Time field to message data

---

CHANGELOG.md
batch.go
cmd/kapacitor/main.go
cmd/kapacitord/run/command.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/config_command.go
cmd/kapacitord/run/server.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
etc/kapacitor/kapacitor.conf
influxdb_out.go
integrations/helpers_test.go
pipeline/batch.go
pipeline/influxdb_out.go
services/httpd/service.go
services/influxdb/config.go
services/influxdb/service.go
services/replay/service.go
task_master.go

Fixes #233 blocked on #155 a bug in the config parser is breaking support for multiple influxdb cluster configs.

Support multiple influxdb clusters [WIP]

---

alert.go
integrations/streamer_test.go
pipeline/alert.go

Allow env from alerta to be a template

---

CHANGELOG.md
services/hipchat/service.go

Check correct HipChat status codes

---

pipeline/map_reduce.go
pipeline/node.go

Updated deprecation warnings with some markdown formatting to make them more prominent.

MapReduce Doc Modification

---

cmd/kapacitor/main.go

Fixes #334 by making the command help nested for each type of recording so it correctly validates flags and prints relevant help messages.

make kapacitor record ... command help nested

---

Dockerfile_build_ubuntu64
build.sh

Fixes some errors in #347.
@nathanielc, I didn't test the changes you asked me to make and ended up breaking the cache functionality.
This PR fixes those issues. Sorry about the hassle!

Fixes to #347

---

build.py

Prevent an rc in the version tag from preventing a nightly build

---

CHANGELOG.md
alert.go
log.go
pipeline/log.go
pipeline/node.go
task.go
wlog/writer.go

Add alert logging + LogNode for easier debugging

---

alert.go
models/batch.go

Fixes issue with alert log and skips empty results returned from a query to InfluxDB

Fix alert log and batches with no values

---

cmd/kapacitor/main.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
node.go
services/task_store/service.go
task.go

Fixes a panic when listing tasks.

Fix issue with list tasks

---

expvar/expvar.go

```
benchmark                               old ns/op       new ns/op     delta
Benchmark_T1000_P5000_Matches-4         2614306617      10704746      -99.59%
Benchmark_T1000_P5000_NoMatches-4       2515589915      10024400      -99.60%
Benchmark_T100_P5000_Matches-4          33235249        13528192      -59.30%
Benchmark_T100_P5000_NoMatches-4        35301480        2377025       -93.27%
Benchmark_T10_P5000_Matches-4           3999232         2545317       -36.35%
Benchmark_T10_P5000_NoMatches-4         4069072         2356547       -42.09%
Benchmark_T10_P500_CountTask-4          4308417         556166        -87.09%
Benchmark_T10_P500000_CountTask-4       171780120       154546757     -10.03%
Benchmark_T1000_P500-4                  17486595152     15440082      -99.91% …
```

Removing expvar keys since it hurts performance and it's unused

---

cmd/kapacitord/run/server_test.go
integrations/data/TestStream_AllMeasurements.srpl
integrations/streamer_test.go

@yosiat Here is the test for making sure a task can process all measurements.

Add test for processing all measurements

---

alert.go
pipeline/alert.go

Adding mode to alert's LogHandler

---

build.py

Enable experimental windows build

---

CHANGELOG.md
client/v1/README.md
client/v1/client.go
client/v1/client_test.go
cmd/kapacitor/main.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/replay/service.go
services/task_store/service.go
task.go

Adds a golang implementation of the HTTP REST API.
Fixes #386
TODO:

[WIP] Add official REST API client

---

CHANGELOG.md
services/influxdb/config.go
services/influxdb/service.go

Allow for subscriptions to be disabled

---

pipeline/stream.go

Signed-off-by: Jon Seymour <jon@wildducktheories.com>

The GroupBy property method is currently documented in the wrong section.

---

build.py

Include tickfmt in packages

---

client/v1/client.go
cmd/kapacitor/main.go
edge.go
etc/kapacitor/kapacitor.conf
examples/scores/scores.sh
integrations/helpers_test.go
join.go
node.go
pipeline/join.go
pipeline/stream.go
services/httpd/logger.go
services/opsgenie/config.go
services/replay/service.go
services/slack/config.go
services/talk/config.go
services/victorops/config.go
task_master.go
tick/cmd/tickdoc/main.go
tick/lex.go
tick/node.go
udf/udf.pb.go
udf/udf.proto

Hi,
I found out the "Go Report Card" and found out some misspells (some that I wrote :( )
Here is the report card:
https://goreportcard.com/report/github.com/influxdata/kapacitor
And I used this tool for fixing the misspells:
https://github.com/client9/misspell

Fixing misspells

---

tick/stateful_expr_test.go

Covering more cases:
* EvalNum: "-4"
* EvalBool: "!true"
* Sanity function calling - count()
* EvalNum for number node

Stateful expression tests

---

build.py
circle.yml
test.sh

Major improvements to `build.py`:
- Now compatible with Python 3
- Now uses Python argparse for cleaner handling of arguments
- Now uses Python logging
- Added function documentation
- Removed a few unneeded functions
- Updated nightly logic to increment minor version
- Added support for building from specific branch or commit
- Added a --release flag, default package output will now contain the commit hash in the version number
- Static builds are now listed as an architecture (and can be built with `--arch=all`)

[WIP] Build script updates

---

tick/stateful_expr_test.go

While implementing the "specialised" stateful expression I found test case I didn't cover
* Supplied reference doesn't exists in BinaryNode{RefNode, NumNode}
* BinaryNode{RefNode,NumNode} value is changed
* BinaryNode{RefNode,NumNode} type is changed from float64 to int64
* BinaryNode{BinaryNode{RefNode,NumNode}, BinaryNode{RefNode,NumNode}}
_I am submitting this as separate PR so the specialised stateful expression won't be big PR_

Adding tests to increase coverage for stateful expression test

---

batch.go
cmd/kapacitord/run/server_test.go
pipeline/batch.go
pipeline/pipeline.go
pipeline/pipeline_test.go
pipeline/sample.go
pipeline/stream.go
stats.go
stream.go
task.go
task_master.go

This PR finishes the last little bit of work needed to finish #445 . 
Changes the names of the nodes to better match docs. 
Fixes #433

Complete name refactor.

---

CHANGELOG.md
cmd/kapacitor/main.go
services/replay/service.go

Fix record query as stream with group by to save data in time order

---

test.sh

There is currently an issue with how Github sets branches for PR's, so disable automatic uploads until more testing can be done.
/cc @nathanielc

Disable S3 Uploads

---

CHANGELOG.md
join.go
pipeline/join.go

This PR finished what #431 started.
Fixes #497 #331

Fix panic on JoinNode missing .as()

---

CHANGELOG.md
influxql.gen.go
influxql.gen.go.tmpl
influxql.go

Log errors about missing or badly type fields, do not panic

---

CHANGELOG.md
batch.go
vendor.yml
vendor/github.com/gogo/protobuf/proto/extensions_gogo.go
vendor/github.com/influxdata/influxdb/CHANGELOG.md
vendor/github.com/influxdata/influxdb/CONTRIBUTING.md
vendor/github.com/influxdata/influxdb/Dockerfile_build_ubuntu32
vendor/github.com/influxdata/influxdb/Dockerfile_build_ubuntu64
vendor/github.com/influxdata/influxdb/Dockerfile_build_ubuntu64_git
vendor/github.com/influxdata/influxdb/appveyor.yml
vendor/github.com/influxdata/influxdb/build.py
vendor/github.com/influxdata/influxdb/client/v2/client.go
vendor/github.com/influxdata/influxdb/influxql/iterator.gen.go
vendor/github.com/influxdata/influxdb/influxql/iterator.gen.go.tmpl
vendor/github.com/influxdata/influxdb/influxql/iterator.go
vendor/github.com/influxdata/influxdb/influxql/select.go
vendor/github.com/influxdata/influxdb/monitor/config.go
vendor/github.com/influxdata/influxdb/monitor/remote_writer.go
vendor/github.com/influxdata/influxdb/monitor/service.go
vendor/github.com/influxdata/influxdb/services/meta/file_windows.go
vendor/github.com/influxdata/influxdb/test.sh
vendor/github.com/influxdata/influxdb/tsdb/meta.go
vendor/github.com/influxdata/influxdb/tsdb/shard.go
vendor/github.com/pkg/errors/errors.go

0.13 requires InfluxDB 0.13, make it clear

---

CHANGELOG.md
alert.go

Fix panic when alert batch is empty

---

alert.go

Added buffer pooling for post handler in alert.
I tried to add benchmark for this, by using `httptest.NewServer` and got: `accept: too many open files`, I tried to increase the maximum file descriptors to 4096 and didn't helped.

Buffer pooling alert post request body buffer

---

CHANGELOG.md
eval.go
integrations/data/TestStream_EvalGroups.srpl
integrations/streamer_test.go
tick/stateful/expr.go

EvalNode honors Groups

---

CHANGELOG.md
integrations/data/TestStream_Eval_Time.srpl
integrations/streamer_test.go
tick/stateful/eval_binary_node.go
tick/stateful/eval_bool_node.go
tick/stateful/eval_float_node.go
tick/stateful/eval_function_node.go
tick/stateful/eval_int_node.go
tick/stateful/eval_reference_node.go
tick/stateful/eval_regex_node.go
tick/stateful/eval_string_node.go
tick/stateful/eval_unary_node.go
tick/stateful/node_evaluator.go
tick/stateful/types.go
tick/stateful/types_test.go

Fixes #555 
Note this PR is based off #567 because both made many changes to the same files and I wanted to avoid conflicts.

Fix time functions in lambda expressions

---

CHANGELOG.md
services/smtp/service.go

Remove panic in SMTP service

---

CHANGELOG.md
services/task_store/service.go
tick/ast/lex.go
tick/ast/lex_test.go

Update lexer to allow numbers without leading zeros

---

cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/task_store/service.go

Fixes #588, task nums correctly counted and tested

---

CHANGELOG.md
services/reporting/service.go

Do not block to send usage stats

---

cmd/kapacitord/run/config.go
services/influxdb/config.go

Handle default values for InfluxDB Service Configs

---

alert.go

Better usage of the alert buffer pool and using the buffer pool in
"json" helper for templates.
- Cleaning the buffer before returning to the pool
- Using the json Encoder and buffer pool in "json" helper for alert
details
```
name                     old time/op    new time/op    delta
_T10_P500_AlertTask-4       144ms ±17%     122ms ± 9%     ~     (p=0.095 n=5+5)
_T10_P50000_AlertTask-4     14.3s ±13%     13.6s ±18%     ~     (p=0.421 n=5+5)
_T1000_P500_AlertTask-4     15.2s ±16%     13.9s ± 7%     ~     (p=0.222 n=5+5)
name                     old alloc/op   new alloc/op   delta
_T10_P500_AlertTask-4      26.2MB ± 0%    23.1MB ± 0%  -11.81%  (p=0.008 n=5+5)
_T10_P50000_AlertTask-4    2.64GB ± 0%    2.32GB ± 0%  -12.06%  (p=0.008 n=5+5)
_T1000_P500_AlertTask-4    2.64GB ± 0%    2.35GB ± …
```

Buffer pooling enhancements

---

CHANGELOG.md
integrations/batcher_test.go
pipeline/batch.go
query.go
task_master.go

Support group by time offset

---

CHANGELOG.md
alert.go

close http respone after hanler alert post

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
services/influxdb/config.go
services/influxdb/service.go

Periodically check if new InfluxDB DBRPs have been created #553

---

CHANGELOG.md
pipeline/alert.go

Fixes #602 Somehow it got removed at somepoint :(
We need to add tests for the SMTP service, but I'll need a good SMTP mock server. For now lets just fix this issue.

Fixes missing To property on email.

---

CHANGELOG.md
services/replay/service.go

Fix missing data url in recording metadata

---

CHANGELOG.md
influxdb_out.go
integrations/streamer_test.go
services/replay/service.go
task_master.go

Fix bug where a failed batch replay would not ever close

---

etc/kapacitor/kapacitor.conf
examples/scores/kapacitor.conf

Update usage language in configs

---

CHANGELOG.md
tick/ast/parser.go
tick/ast/parser_test.go
tick/eval_test.go

Fix issue where function params could not be expressions

---

CHANGELOG.md
influxql.gen.go
influxql.gen.go.tmpl
integrations/data/TestStream_HoltWinters.srpl
integrations/streamer_test.go
pipeline/influxql.go

Fix missing tags on batch influxql

---

CHANGELOG.md
cmd/kapacitor/main.go

Add -skipVerify flag to kapacitor cmd to skip SSL verification

---

CHANGELOG.md
integrations/batcher_test.go
integrations/data/TestBatch_JoinOn.0.brpl
integrations/data/TestBatch_JoinOn.1.brpl
join.go
models/batch.go
models/point.go
pipeline/node.go

Fix panic when joining on dimensions with batches

---

CHANGELOG.md
batch.go
pipeline/node.go
pipeline/stats.go
stats.go

Align deadman times

---

cmd/kapacitord/run/command.go
cmd/kapacitord/run/config_command.go
server/config.go
server/config_test.go
server/server.go
server/server_helper_test.go
server/server_test.go

Reorganize server into its own package

---

cmd/kapacitor/main.go

Fix typos in kapacitor cli

---

CHANGELOG.md
services/influxdb/service.go

Fix susbcription error for db names with quotes

---

server/server.go

Use name based services

---

batch.go
client/v1/client.go
influxdb/client.go
influxdb/client_test.go
influxdb/point_test.go
influxdb_out.go
integrations/helpers_test.go
models/batch.go
models/point.go
server/server.go
services/influxdb/config.go
services/influxdb/service.go
services/replay/service.go
task_master.go

Refactors the InfluxDB service so the client that is used can be switched out.

InfluxDB Service pluggable client. 

---

etc/logrotate.d/kapacitor

Fix logrotate does not work with default log file.

---

etc/kapacitor/kapacitor.conf

update deadman comment

---

query.go

Better error message for invalid queries

---

build.py

This fixes an issue where CircleCI builds are frequently timing out. Basically the race enabled test suite would take longer than expected and CircleCI would abort the test since no output was received. Now with this change test output is sent to STDOUT immediatly instead of after the entire test suite has finished.
/cc @rossmcdonald

change build.py to print the output of the tests as they are run

---

CHANGELOG.md
alert.go
integrations/data/TestStream_Alert_NoRecoveries.srpl
integrations/streamer_test.go
pipeline/alert.go

Add ability to supress OK alerts

---

CHANGELOG.md
task_master.go

Fix panic from race in task master

---

auth/auth.go
services/httpd/handler.go

Make sure the database name can't do path traversal to get more permissions.

Ensure unique and safe mapping from db name to db resource

---

global_stats.go

Add ID tags to all Kapacitor stats.

add ID tags to stats points

---

examples/telegraf/generic_stream_example.tick
examples/telegraf/zookeeper/zookeeper_data_size_batch.tick
examples/telegraf/zookeeper/zookeeper_data_size_stream.tick
examples/telegraf/zookeeper/zookeeper_latency_batch.tick
examples/telegraf/zookeeper/zookeeper_latency_stream.tick

Have alerts for amount of data held and API latency

Add zookeeper tickscripts

---

influxdb_out.go

Change influxdb stats to not count points written on error

---

CHANGELOG.md
services/influxdb/config.go
services/influxdb/service.go
services/influxdb/service_test.go

Specifically this PR fixes an issue where subscriptions + tokens would not work with more than one InfluxDB cluster.
Also includes nearly full coverage tests for the InfluxDB linkSubscriptions code

Add tests for InfluxDB service

---

client/API.md

Update API docs

---

pipeline/eval.go
pipeline/influxql.go
pipeline/node.go

This comes from @beckettsean review of the docs. https://github.com/influxdata/docs.influxdata.com/pull/615

Update docs for eval node

---

CHANGELOG.md
integrations/batcher_test.go
integrations/streamer_test.go
pipeline/where.go
where.go

Fix side-effecting WhereNode, fixes #842

---

pipeline/derivative.go

Fixes https://github.com/influxdata/docs.influxdata.com/issues/596

Update derivative documentation to clarify on relation to InfluxQL

---

pipeline/batch.go
pipeline/http_out.go
pipeline/influxql.go
pipeline/node.go

Update docs based on various suggetions

---

CONTRIBUTING.md

@nathanielc @rkuchan Some updates to the contributing guide as part of the docs cleanup. Any suggestions?

A few small cleanups to CONTRIBUTING.md

---

pipeline/node.go

Port changes from https://github.com/influxdata/docs.influxdata.com/pull/625/files. I made three additional changes too.

Update with changes from docs #625

---

etc/kapacitor/kapacitor.conf

syntactical fix in slack section

---

CHANGELOG.md
alert.go
integrations/batcher_test.go
integrations/streamer_test.go
pipeline/alert.go

Add support for setting the alert message as a field

---

CHANGELOG.md
influxdb_out.go
integrations/streamer_test.go
pipeline/influxdb_out.go

Add ability to create database and rp with InfluxDBOutNode

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf

Fixing typo within example configuration file

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
services/influxdb/config.go
services/influxdb/service.go

Add config to override http subcription settings on a per cluster basis

---

ALERT_DESIGN.md

We should probably flesh out this doc with more of the existing alert design. For now this doc contains the proposed enhancements to the alerting system.
@joelegasse

[WIP] Alerting system design doc

---

CHANGELOG.md
server/server.go

Fail startup when we fail to save the cluster/server IDs

---

CHANGELOG.md
server/server.go

Create data_dir if missing

---

CHANGELOG.md

Just a minor typo fix in the change log.

fix a typo in the change log

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/client_test.go
cmd/kapacitor/main.go
integrations/helpers_test.go
server/server.go
server/server_test.go
services/alerta/service.go
services/hipchat/service.go
services/influxdb/service.go
services/k8s/client/client.go
services/k8s/client/types.go
services/k8s/service.go
services/opsgenie/service.go
services/pagerduty/service.go
services/sensu/service.go
services/servicetest/config.go
services/servicetest/service.go
services/slack/service.go
services/smtp/service.go
services/talk/service.go
services/telegram/service.go
services/victorops/service.go
usr/share/bash-completion/completions/kapacitor

Fixes #957 
See updated API docs for new API endpoint for testing service integrations.
Note this PR is based off #928 and will need to be rebased once that is merged.

[WIP] Add test endpoints for services

---

influxdb/client.go
services/influxdb/service.go
services/influxdb/service_test.go

close influxdb clients

---

CHANGELOG.md
expvar/expvar.go
global_stats.go
server/config.go
services/influxdb/service.go

Fixes #955
The logic for counting the number of subscriptions was broken. 
This also fixes an issue with the InfluxDB ApplyDefaults not working correctly.

Fix the number of subscriptions stat

---

examples/telegraf/disk/disk_alert_batch.tick
examples/telegraf/disk/disk_alert_stream.tick

Fix disk alert example

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
server/config.go
server/server.go
server/server_test.go
task_master.go

Fix inconsistency with default rp on /write

---

CHANGELOG.md
integrations/data/TestStream_Window_Count.srpl
integrations/streamer_test.go
pipeline/window.go
window.go
window_test.go

Fixes #327 
Adds support for windowing based on count, via the `periodCount` and `everyCount` WindowNode properties.

Adds support for windowing based on count

---

CHANGELOG.md
edge.go

Fixes #1045 
Fix panic during replays.

Fix panic during replays

---

CHANGELOG.md
build.py

issue #1043 wrong file mode on kapacitor logrotate configuration

---

build.py

Fixes https://github.com/influxdata/kapacitor/issues/1059

Fix packaging arguments

---

cmd/kapacitor/main.go
vendor.list
vendor/github.com/ghodss/yaml/.gitignore
vendor/github.com/ghodss/yaml/.gitrepo
vendor/github.com/ghodss/yaml/.travis.yml
vendor/github.com/ghodss/yaml/LICENSE
vendor/github.com/ghodss/yaml/README.md
vendor/github.com/ghodss/yaml/fields.go
vendor/github.com/ghodss/yaml/yaml.go
vendor/github.com/ghodss/yaml/yaml_test.go

See http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/

Make YAML and JSON play nice for alert handlers

---

alert.go
cmd/kapacitor/main.go
global_stats.go
http_out.go
influxdb/client.go
log.go
pipeline/node.go
pipeline/pipeline.go
replay.go
result.go
server/config.go
server/server.go
server/server_test.go
services/influxdb/service.go
services/replay/service.go
services/sensu/service.go
services/task_store/service.go
task.go
task_master.go
tick/ast/lex.go
tick/eval.go
udf.go
udf/server.go

Miscellaneous lint cleanup

---

CHANGELOG.md
alert.go
alert/topics.go
cmd/kapacitor/main.go
server/server_test.go
services/alert/dao.go
services/alert/service.go
services/task_store/service.go
task_master.go
usr/share/bash-completion/completions/kapacitor

Restore anonymous topics and  assert consistency between anon topics and normal topics.
Fixes #744

Restore anonymous topics 

---

pipeline/alert.go

Small typo fix for the alert node documentation

---

alert/DESIGN.md
alert/topics.go
alert/types.go
client/v1/client.go
client/v1/client_test.go
cmd/kapacitor/main.go
edge.go
node.go
server/server.go
server/server_test.go
services/alert/handlers.go
services/alert/service.go
services/influxdb/service.go
services/influxdb/service_test.go
services/reporting/service.go
services/stats/service.go
services/task_store/service.go
services/udp/service.go
task_master.go
vars/stats.go
vars/vars.go

Adds `publish` and `stateChangesOnly` handler actions.
Exposes topic collected counts.

Several alert usability fixes

---

CHANGELOG.md
influxql.go

Fixes #872

---

CHANGELOG.md

update CHANGELOG for past change fixes #1086

---

cmd/kapacitor/main.go

Add list of handlers to output of show topic

---

CHANGELOG.md
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64

Go version 1.7.4 -> 1.7.5

---

CHANGELOG.md
alert.go
alert/types.go
http_out.go
integrations/batcher_test.go
integrations/helpers_test.go
integrations/streamer_test.go
models/batch.go
models/point.go
models/result.go
server/server_test.go
services/alert/handlers.go
services/alerta/service.go
services/opsgenie/service.go
services/pagerduty/service.go
services/victorops/service.go

Standardized underlying models for result data

---

CHANGELOG.md
alert.go
pipeline/alert.go

Expose server info in alert templates

---

CHANGELOG.md
alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
server/config.go
server/server.go
server/server_test.go
services/alert/service.go
services/pushover/config.go
services/pushover/pushovertest/pushovertest.go
services/pushover/service.go
task_master.go

The PR adds support for pushing alerts to the Pushover API.

Add Pushover integration for Kapacitor

---

CHANGELOG.md
alert.go
combine.go
derivative.go
eval.go
expvar/expvar.go
flatten.go
group_by.go
http_out.go
influxql.go
integrations/data/TestStream_Cardinality.srpl
integrations/streamer_test.go
join.go
k8s_autoscale.go
node.go
sample.go
server/server_test.go
where.go
window.go

Reverts influxdata/kapacitor#1240

Revert "Revert "WIP: Add cardinality stat to each node type.""

---

server/server.go

Services should be closed in reverse order. Currently all tasks are stopped before service are closed so this hasn't been an issue. Now that the alert service is processing events, we need to close the services in reverse order so that its dependencies are still open when it is being closed.

Close services in reverse order

---

CHANGELOG.md
node.go
task.go

Dot labels are make use of xlabel and fix quoting issues

---

alert/topics.go

Fix race in topics on pointer dereference

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf

Start with a blank URL; Chronograf provides a placeholder

---

eval.go
pipeline/eval.go

Fixing typo in eval node code

---

CHANGELOG.md
services/task_store/service.go

Fix missing vars data when listing tasks

---

CHANGELOG.md
influxdb/client.go

Merge back v1.2 fixes

---

udf/agent/agent.go
udf/agent/examples/mirror/mirror.go
udf/agent/examples/moving_avg/moving_avg.go
udf/agent/examples/outliers/outliers.go

Fix snaphost typo in UDF agent code

---

CHANGELOG.md
server/server.go

Fix panic when the process cannot stat the data dir

---

server/config.go
server/server.go
server/server_test.go
services/file/config.go
services/scraper/service.go
services/static/config.go

Update files and static to files-discovery and static-discovery

---

CHANGELOG.md
expr.go
integrations/data/TestStream_Eval_Missing.srpl
integrations/streamer_test.go
services/alert/handlers.go
task_master.go
tick/ast/types.go
tick/ast/types_test.go
tick/stateful/eval_binary_node.go
tick/stateful/eval_bool_node.go
tick/stateful/eval_duration_node.go
tick/stateful/eval_float_node.go
tick/stateful/eval_function_node.go
tick/stateful/eval_int_node.go
tick/stateful/eval_lambda_node.go
tick/stateful/eval_reference_node.go
tick/stateful/eval_regex_node.go
tick/stateful/eval_string_node.go
tick/stateful/eval_unary_node.go
tick/stateful/expr.go
tick/stateful/functions.go
tick/stateful/node_evaluator.go
tick/stateful/scope.go

This PR introduces a type system for builtin functions. Was built to make https://github.com/influxdata/kapacitor/issues/1203 easier to implement.
Todo:
Todo Type System:
Todo Missing and isPresent:

WIP: Add type signature to built-in functions

---

etc/kapacitor/kapacitor.conf
server/config.go
server/server.go
server/server_test.go
services/file_discovery/config.go
services/file_discovery/service.go
services/static_discovery/config.go
services/static_discovery/service.go

This PR contains some small code changes and fixes for the scraping services.
* Rename a few things to be consistently singular

Minor Scraper Fixes

---

services/alert/handlers.go
services/alert/service.go

Fixes https://github.com/influxdata/kapacitor/issues/1364

Fix http post handler API

---

CHANGELOG.md
state_tracking.go

Add missing working_cardinality stats on state* nodes

---

CHANGELOG.md
influxql.go
integrations/data/TestStream_InfluxQLNodeMissingValue.srpl
integrations/streamer_test.go

Fix panic in InfluxQL node with missing field

---

CHANGELOG.md
cmd/kapacitor/main.go

Allow for `.yml` file extensions w/ topic handler

---

Gopkg.lock
Gopkg.toml

The Azure deps were not properly constrained in the Gopkg.toml file.

Update Gopkg for both Azure deps

---

CHANGELOG.md
services/slack/service.go

Not sure how I missed this in the first place.

Add ProxyFromEnvironment to slack services

---

CHANGELOG.md
batch.go
pipeline/batch.go

Add linear support for QueryNode.fill

---

server/config.go

This allows any type that implements text.Unmarshaler to be correctly overridden via env vars.

Use text Unmarsharler instead of checking for specific types in applyEnvOverrides

---

CHANGELOG.md
integrations/streamer_test.go
server/server_test.go
services/pagerduty/service.go

Merge 1.3.2 into master

---

services/diagnostic/internal/log/field.go
services/diagnostic/internal/log/log_test.go

Fixes https://github.com/influxdata/kapacitor/issues/1576

Fix panic on nil error field

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
http_post.go
integrations/batcher_test.go
integrations/streamer_test.go
server/config.go
server/server.go
server/server_test.go
services/httppost/config.go
services/httppost/httpposttest/server.go
services/httppost/service.go

Add support for custom HTTP post bodies via a template system

---

CHANGELOG.md

Just realized that I forgot to do this :(

Add Changelog entry for logging refactor

---

CHANGELOG.md
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64

Update Go to 1.9.1

---

CHANGELOG.md
alert/types.go
integrations/batcher_test.go
integrations/streamer_test.go
server/server_test.go

Add PreviousLevel to Alert Event messages as mentioned in #1408

Added PreviousLevel to Alerts

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go

Includes the .Duration for the Message and Details on alert #1605

---

CHANGELOG.md
services/diagnostic/log.go

Add `\n` following each JSON log line

---

CHANGELOG.md
build.py

Fix missing shadow-utils dep in rpm package

---

CHANGELOG.md
build.py

Force tar files to be owner by root and group root.

---

CHANGELOG.md
scripts/kapacitor.service
scripts/post-install.sh
scripts/post-uninstall.sh

Fixes #1428 
Fixes #1440
Replaces PR #1161

Fix various issues with packaging

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/client_test.go
server/server_test.go
services/alert/api.go
services/alert/service.go

Promote alerts API to stable v1 paths

---

CHANGELOG.md
services/mqtt/config.go

Fix invalid default MQTT config

---

client/v1/client.go
services/diagnostic/api.go

Move logs API underneath /v1preview

---

pipeline/json.go

Few small fixes for converting deadman

Update pipeline JSON marshaling for deadman & stats

---

services/diagnostic/handlers.go
services/diagnostic/service.go

Some small fixes to make extending Diagnostics easier

---

CHANGELOG.md
services/diagnostic/api.go

Fix log API accept <-> content-type header issue

---

client/API.md

Remove references to actions from API docs

---

DESIGN.md

- [ x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

Propose small spelling changes

---

client/v1/client.go
cmd/kapacitor/main.go
cmd/kapacitord/main.go
cmd/kapacitord/run/command.go
integrations/helpers_test.go
server/server.go
server/vars/vars.go

Added oss to the appropriate locations to identify the oss platform

---

CHANGELOG.md
alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
integrations/testdata/TestStream_AlertRecovery.srpl
pipeline/alert.go
pipeline/alert_test.go
pipeline/json_test.go
pipeline/tick/alert.go
pipeline/tick/alert_test.go
server/config.go
server/server.go
server/server_test.go
services/alert/service.go
services/diagnostic/handlers.go
services/diagnostic/service.go
services/opsgenie2/config.go
services/opsgenie2/opsgenie2test/opsgenietest.go
services/opsgenie2/service.go
task_master.go

Fixes #1821 
Fixes #1819 
Fixes #1708 
TODO

Update OpsGenie to use v2 API

---

flatten.go

Fix log spelling error

---

server/server.go
services/httpd/service.go

Fixes issue where the load service would not work if authentication was enabled.

Use special http handler for load service that circumvents auth etc.

---

CHANGELOG.md
server/server_test.go
services/task_store/util.go

Fix dynamic type not working for vars

---

CHANGELOG.md
node.go
pipeline/eval.go
pipeline/json_test.go
pipeline/node.go
server/server_test.go
task.go
tick/eval.go

Add .quiet to all nodes

---

client/API.md

Added note based on multiple issues pointing out need to disable and enable when using the PATCH method.

Update PATCH method with note about re-enabling.

---

CHANGELOG.md
server/server_test.go
services/alert/api.go

Fix deleting topic handler with same name as topic

---

services/slack/service.go

fix slack service test

---

services/kafka/config.go

added default as name for the default kafka config

---

CHANGELOG.md
join.go

Add Barrier support to the Join node

---

integrations/streamer_test.go
server/server_test.go

update pagerduty2 test case for links

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/tick/alert.go
pipeline/tick/alert_test.go
server/server_test.go
services/sensu/sensutest/sensutest.go
services/sensu/service.go

Add Sensu metadata support

---

CHANGELOG.md
pipeline/alert.go
pipeline/alert_test.go
pipeline/json_test.go
pipeline/tick/alert.go
pipeline/tick/alert_test.go
services/httppost/service.go

Fixes: https://github.com/influxdata/kapacitor/issues/532

Add ability to skip ssl verification with an alert post node

---

edge/stats.go

The previous fix to delete group stats deleted the stats at collect instead of emit. This meant that there was a small possibility that points that were still buffered in the edge would recreate the stats structures for groups that had just been deleted, thus circumventing the stats deletion. 
This change makes it so that stats are deleted during the emit phase so that there is no opportunity for buffered points to recreate the stats.

fix(edge): delete group stats on emit not collect

---

cmd/kapacitor/main.go

Change CLI to support JSON formatted for service

---

build.py

feat(build): switch from md5 to sha256

---

examples/load/README.md

fix small typo

---

CHANGELOG.md
udf/agent/examples/moving_avg/moving_avg.py
udf/agent/py/kapacitor/udf/agent.py
udf/agent/py/setup.py

Noticed some minor bugs while working with the Python3 UDF implementation.
The Changes in this PR fix them.

UDF Agent Python3 fixes

---

.circleci/config.yml

__What__
- Update CircleCI `config.yml` to use workflows.
- Update CircleCI `config.yml` to be able to execute workflows for a git tag.
__Tests__
- Validated updated yml file using https://codebeautify.org/yaml-validator
- Used `circleci` cli to validate config file: 
from influxdata/kapacitor directory execute
```
circleci config validate
```
- CircleCI build successfully run for `build` job
- CircleCI build successfully run for `release` job

chore: Update CircleCI config to use workflows

---

CHANGELOG.md

chore: Update release date for v1.5.6

---

replay.go

kapacitor: add missing err check of buf scanner.

---

services/httppost/config.go
services/httppost/service.go

This fixes a minor possible race in the url template.

fix: fix minor race in url template

---

CHANGELOG.md

Update Changelog for 1.5.7 release.

---

CHANGELOG.md

Update changelog for https://github.com/influxdata/kapacitor/pull/2409

Chore: Update CHANGELOG.md

---

pipeline/alert_test.go
pipeline/tick/alert_test.go
server/server_test.go
services/zenoss/service.go

Fixes https://github.com/influxdata/kapacitor/issues/2507.

fix: Zenoss testing

---

CHANGELOG.md
influxdb/client.go
influxdb/token_client.go
server/server.go
server/server_test.go
services/influxdb/config.go
services/influxdb/service.go

feat: shared secret auth to influxdb in OSS

---

client/v1/client.go
cmd/kapacitord/run/command.go
http/transport.go
influxdb/client.go
services/alerta/service.go
services/bigpanda/service.go
services/discord/service.go
services/httppost/service.go
services/influxdb/service.go
services/k8s/client/client.go
services/load/service.go
services/sideload/service.go
services/slack/service.go
services/swarm/client/client.go

This allows blacklisting CIDR ranges for various post/get operations.

feat: flag to allow blacklisting CIDR ranges

---

services/config/service_test.go

test: fix flaky TestService_GetConfig #1367

---

.circleci/config.yml
build.py

build: include signatures and checksums in release uploads

---

CHANGELOG.md

chore: Update changelog for v1.6.2 release

---

.circleci/config.yml

build: Import the gpg key required for package signing

---

.circleci/config.yml
build.py

* remove nested docker container in favor of cross-builder
* build and sign but don't upload for 'test' tags
* archive build artifacts in circle

build: update build logic

---

.circleci/config.yml
build.py

build: remove nested containerization from tests

---

.circleci/config.yml
scripts/CHANGELOG_frozen.md

Do not yet replace the existing changelog though.

chore: add automatic changelog generation

---

build.py

This increases the cgo stack size of builds.

build: larger cgo stack

---

examples/telegraf/README.md

Use latest version of documentation for telegraf examples

---

.circleci/config.yml
build.py

Only adjust cgo stack size on linux.

build: Darwin fix

---

services/fluxtask/service.go
task/config.go
task/fluxlocal/query.go

This is to fix flux being broken in nightly.
@btasker This should help you out.

fix: flux limits and bad flux httpclient

---

tlsconfig/config.go

DES based ciphers were depreciated in v1.6.3 but due to a bug this only applied
to when those ciphers were specified in the config file.
This fully removes them, and also removes RC4 based ciphers and TLS<1.2.

security(TLS): properly depreciate TLS<1.2, DES and RC4 based ciphers

---

go.mod
go.sum

This is a fix for this SASL bug https://github.com/Shopify/sarama/pull/2234

chore(kafka): upgrade sarama library to 1.34.0

---

CHANGELOG.md

Update CHANGELOG.md for 1.6.5 release

chore(changelog): CHANGELOG.md for v1.6.5 release

---

build.py

testing: fail fast on tests

---

services/alert/migrate_topic_store.go

Correct log messages concerning Topic Store
upgrade and downgrade.

fix: correct error messages for upgrade/downgrade

---

.circleci/config.yml
Dockerfile_build_ubuntu64

Closes https://github.com/influxdata/edge/issues/584

chore(build): upgrade Go to 1.20.13

---

.circleci/config.yml
Dockerfile_build_ubuntu64
go.sum

Closes https://github.com/influxdata/edge/issues/645

chore(build): upgrade Go to 1.21.9
