influxdata/kapacitor

cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
services/reporting/config.go
services/reporting/service.go
stats.go

`enterprise-client` will soon be repurposed for the on-prem solution, so we have renamed the existing `enterprise-client` to `usage-client`. It provides the same interface, but the backend endpoints for everything except anonymous usage reporting have been no-oped. I attempted to remove stats reporting from Kapacitor, however it seems that `client.StatsData` is used internally to facilitate writing TICK scripts against Kapacitor's own stats. Since this will require a bit more care than originally thought, for the time being this patch only switches the repos so that everything is reported to `usage.influxdata.com` instead of `enterprise.influxdata.com` (since we are repurposing that subdomain as well).

Change 'enterprise-client' to 'usage-client'

---

CHANGELOG.md
cmd/kapacitord/run/server_test.go
edge.go
node.go
services/task_store/service.go
task.go
task_master.go

Adds the throughput number to the DOT ouput of the `kapacitor` show command. This way you can get a quick glance without having to store and then query the internal stats.
Example DOT output:
```
digraph udp_drop {
stream0 -> stream1 [label="63921"];
stream1 -> groupby2 [label="143"];
groupby2 -> derivative3 [label="143"];
derivative3 -> window4 [label="142"];
window4 -> map5 [label="2"];
map5 -> reduce6 [label="2"];
reduce6 -> alert7 [label="2"];
}
```
Read as 63921 points have been sent from stream0 to stream1. In this case meaning that the dbrp of the task has received 63921 points. Only 143 points where passed from stream1 to groupby2 meaning that only 143 points matched the from and where conditions of the task.
These throughput numbers are only displayed if the task is executing.

Add edot to show

---

CHANGELOG.md
cmd/kapacitor/main.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/replay/service.go
task_master.go

With the refactor in #86 the replay engine wasn't properly draining the TaskMaster to that the tasks could run to completion.

Add tm.Drain to task complete in replay

---

CHANGELOG.md
integrations/streamer_test.go
tick/TICKscript.md
tick/eval.go
tick/lex.go
tick/lex_test.go
tick/parser.go
tick/parser_test.go

Fixes #107 
You can now use vars in TICKscripts like this
```
var cpuThreshold = 10.0
stream.from()....
.alert()
.crit(lambda: "value" > cpuThreshold)
```
Vars can be any primitive type within TICKscript, namely: bools, numbers, string, durations, and regexp.

Enable using TICKscript vars inside of lambda expressions

---

alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/opsgenie/config.go
services/opsgenie/service.go
task_master.go

Implements #71 
I am running this code in our production environment, and have been getting OpsGenie alerts since 12/18/2015.
Usage:
```
stream
.from().measurement('cpu')
.groupBy('host')
.window()
.period(10s)
.every(10s)
.mapReduce(influxql.count('idle'))
.alert()
.id('kapacitor/{{ .Name }}/{{ index .Tags "host" }}')
.info(lambda: "count" > 6.0)
.warn(lambda: "count" > 7.0)
.crit(lambda: "count" > 8.0)
.opsGenie()
.ogTeams('test_team,another_team')
.ogRecipients('test_recipient,another_recipient')
```
Configuration:
```
[opsgenie]
enabled = false
api-key = ""
teams = ""
recipients = ""
url = "https://api.opsgenie.com/v1/json/alert"
recovery_url = "https://api.opsgenie.com/v1/json/alert/note"
global = false
```
This is my first run at working with Go, …

added OpsGenie service for alerting

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/influxdb_out.go
tick/cmd/tickdoc/main.go
update_tick_docs.sh

Fixes #118 
With this change each alert handler is appropriately scoped so you do not have to worry about name conflicts. You can now add multiple handlers of the same type. 
For example:
```
stream
.from().measurement('cpu')
.groupBy('host')
.window()
.period(10s)
.every(10s)
.mapReduce(influxql.count('idle'))
.alert()
.id('kapacitor/{{ .Name }}/{{ index .Tags "host" }}')
.info(lambda: "count" > 6.0)
.warn(lambda: "count" > 7.0)
.crit(lambda: "count" > 8.0)
.slack()
.channel('#alerts')
.slack()
.channel('@jim')
```

Allow for multiple alert handlers of the same type

---

alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/hipchat/config.go
services/hipchat/service.go
task_master.go

Implements #119 
This code has been tested and has successfully sent alerts to HipChat as of 12/28/2015.
Usage:
```
stream
.from().measurement('cpu')
.groupBy('host')
.window()
.period(10s)
.every(10s)
.mapReduce(influxql.count('idle'))
.alert()
.id('kapacitor/{{ .Name }}/{{ index .Tags "host" }}')
.info(lambda: "count" > 6.0)
.warn(lambda: "count" > 7.0)
.crit(lambda: "count" > 8.0)
.hipChat()
.room('1234567')
.token('testtoken1234567')
```
Configuration:
```
[hipchat]
enabled = false
url = "https://subdomain.hipchat.com/v2/room"
room = ""
token = ""
global = false
```

Added HipChat service for alerting.

---

CHANGELOG.md
services/task_store/service.go

use t.Name since it always exists

---

alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/alerta/config.go
services/alerta/service.go
task_master.go

Implements integration with [alerta.io](http://alerta.io)
The code has been tested with a local instance of alerta.
Usage:
```
stream
.from().measurement('cpu')
.groupBy('host')
.window()
.period(10s)
.every(10s)
.mapReduce(influxql.count('idle'))
.alert()
.id('{{ index .Tags "host" }}')
.message('kapacitor/{{ .Name }}/{{ index .Tags "host" }} is {{ .Level }}')
.info(lambda: "count" > 6.0)
.warn(lambda: "count" > 7.0)
.crit(lambda: "count" > 8.0)
.alerta()
.token('testtoken1234567')
.resource('serverA')
.event('CPU Idle')
.environment('production')
```
Configuration:
```
[alerta]
enabled = false
url = ""
token = ""
environment = ""
origin = "kapacitor"
```

Alerta.io Integration

---

CHANGELOG.md
cmd/kapacitor/main.go
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
http_out.go
services/httpd/handler.go

Fixes #163 
Turns out Telegraf ignores any errors to the Create Database call so we don't have to mock it. I also checked the python client and it does not explicitly check that the database exists either. 
I like this behavior because the actual write request returns its own success/failure codes and so there should not be any need to explicitly check that a database exists. Just write the data...

Remove incompatible api pathing

---

CHANGELOG.md
alert.go
eval.go
expr.go
pipeline/node.go
stream.go
tick/functions.go
where.go

Fixes #141
Now there are 6 functions for working with time in the lambda expressions:
* minute -- the minute within the hour [0,59]
* hour -- the hour within the day [0,59]
* weekday -- the weekday within the week [0,6] 0 is Sunday
* day -- the day within the month [1,31]
* month -- the month within the year [1,12]
* year -- the year.
Example using the deadman's switch:
```javascript
//Trigger deadman's switch only between 8am-5pm local time.
stream.deadman(0,10s,lambda: hour("time") >= 8 AND hour("time") <= 17)
```
Note this is based off the time of the data not the current system time.
Implementing a `cron` function was a little more work so I have created a new issue to track adding a cron time function.  #168
Adding these functions makes me think we should add the ability to perform …

Add time of day expressions

---

CHANGELOG.md
alert.go
cmd/kapacitord/run/server.go
integrations/helpers_test.go
integrations/streamer_test.go
pipeline/alert.go
result.go
services/smtp/service.go
task_master.go

Fixes #196 and Fixes #75 
Now the alert node has a `details` property that can be formatted HTML containing details of the alert. The details property is used as the body of email alerts.

add alert support for Details property

---

.gitignore
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64
Dockerfile_build_ubuntu64_git
build.py
build.sh
circle-test.sh
circle.yml
gobuild.sh
test.sh

This takes the work done for InfluxDB. Now Kapacitor can be tested against various envs.
There is an experimental arm env which uses qemu. If its too slow we will have to remove it but for now I would like to see if its possible.

Add test.sh for testing various envs

---

DESIGN.md

Documenting the internal design of Kapacitor for posterity.

Draft of Kapacitor design doc [WIP]

---

alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/talk/config.go
services/talk/service.go
task_master.go

[Talk](https://jianliao.com/site?lang=en) is a very popular chat tools in China, our team is using it as a endpoint to accept alerting.

Added Talk service for alerting.

---

build.py

Fixes:
- Moved nightly versioning to be set after CLI parsing due to an error that would occur if the `--nightly` was specified before `--version`
- Moved `go get` to be run for every platform, as some projects have platform-specific includes (and I didn't know `go get` was affected by the `GOOS` env variable)

Minor build updates

---

build.py

Switched nightly versioning to use a tilde instead of a period for easier upgrade paths.
/cc @nathanielc

Switch nightly versioning format

---

.gitignore
CHANGELOG.md
integrations/data/TestStream_Shift.srpl
integrations/streamer_test.go
pipeline/node.go
pipeline/shift.go
shift.go
task.go
tick/eval.go
tick/eval_test.go
tick/parser_test.go

Example from tests:
```javascript
var period  = 5s
var data  = stream
.from()
.measurement('cpu')
var past = data
.window()
.period(period)
.every(period)
.align()
.mapReduce(influxql.count('value'))
//shift values from the past forward so they can be compared with current values.
.shift(period)
var current = data
.window()
.period(period)
.every(period)
.align()
.mapReduce(influxql.count('value'))
past.join(current)
.as('past', 'current')
.eval(lambda: "current.count" - "past.count")
.keep()
.as('diff')
.httpOut('TestStream_Shift')
```

Add shift node so values from different times can be joined

---

CHANGELOG.md
edge.go
node.go
noop.go
pipeline/node.go
pipeline/noop.go
pipeline/stats.go
services/deadman/config.go
stats.go
task.go

Fixes #190 both the groupBy issues and the fact that the `where` clause was ignored.
These changes should make the deadman's switch much more intuitive and easy to use.

deadmans stats by group and for emitted not collected

---

CHANGELOG.md
integrations/data/TestStream_WindowMissing.srpl
integrations/streamer_test.go
window.go

Fixes #221 
Thanks @yosiat for the detailed steps to reproduce. 
The bug was that the window node could not handle gaps in the data set larger than the `every` value. It assumed that there was always at least on point in each emitted window. As a result the emitted times would get behind the data times and extra points would make it into each window. Again thanks for the detailed write up. You will notice a few tests have been added for this scenario.

fix window errors when there are missing windows in the data stream

---

README.md

Updated documentation links in the README to point to the Kapacitor 0.10 documentation.
Fixes #252

Update Readme Documentation Links

---

build.py

A few updates ported from the InfluxDB build script:
- Improved handling of ARM architectures, where `armhf`, `armel`, and `arm64` are broken out.
- Removed the `--goarm` and `--pkgarch` build flags.
- Removed buildTime from linker flag specification so that reproducible builds can be created.
- `go get` is not project-specific, since InfluxDB and Telegraf use `gdm` and Kapacitor uses Go vendoring
- Removed the per-platform `go get` call since dependencies are vendored (or pinned, as is the case with InfluxDB)

Updates to build.py

---

CHANGELOG.md
alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
services/sensu/config.go
services/sensu/service.go

@brettdh I believe I have addressed all the issues. ATM it is not easy to use docker to create a sensu client for full integration testing. The unit tests have been updated to use a raw TCP socket and the code has been tested against a real Sensu client and is behaving correctly. 
Note in addition to the sensu changes a small change was added to the alert node to count triggered alerts.

Sensu fixes

---

build.py
circle.yml
test.sh
vendor/github.com/influxdb/influxdb/cluster/internal/data.pb.go
vendor/github.com/influxdb/influxdb/services/copier/internal/internal.pb.go
vendor/github.com/influxdb/influxdb/services/meta/internal/meta.pb.go
vendor/github.com/influxdb/influxdb/tsdb/internal/meta.pb.go

This change brings back parity to InfluxDB build script.

Minor change to build.py

---

alert.go
services/pagerduty/service.go
task_master.go

Improvements to the PagerDuty service integration:
- Adds the concept of alert levels that correspond to the PagerDuty `trigger` and `resolved` events
- Includes the alert ID in the PagerDuty requests, instead of opening a new incident with every alert
Fixes #288

PagerDuty Enhancement

---

CHANGELOG.md
batch.go

batch error handling

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
services/influxdb/config.go
services/influxdb/service.go

Support detailed TLS config for connecting to InfluxDB

---

CHANGELOG.md
batch.go
integrations/streamer_test.go
node.go
pipeline/pipeline.go
services/replay/service.go
services/task_store/service.go
stats.go
task.go

Deadman fixes

---

CHANGELOG.md
alert.go
etc/kapacitor/kapacitor.conf
pipeline/alert.go
services/hipchat/config.go
services/hipchat/service.go
services/slack/config.go
services/slack/service.go
services/smtp/config.go
services/smtp/service.go
task_master.go

Fixes #340 Now instead of global = true for an alert handler also setting stateChangesOnly there is an explicit settting `state-changes-only` that must also be set. 
This help to remove the confusion caused by the side effect of setting global = true for Email, Slack or HipChat.
Fixes #332

Decouple global setting from state-changes-only

---

Dockerfile_build_ubuntu64
build.sh

The docker build is rather punishing on 4G bandwidth consumption.
This change allow the user to cache the /root/go/src if they so choose, but
default to not using such a cache.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>

Allow /root/go/src to be cached during docker build

---

node.go
services/task_store/service.go
task.go
task_master.go

See issue - #321 
Currently I implemented the input nodes, I am waiting for feedback about this and a suggestion of how to implement the metrics fetching for the outputs.

[WIP] Add stats to tasks

---

CHANGELOG.md
cmd/kapacitord/run/config.go
cmd/kapacitord/run/config_test.go

This fixes #348.
In particular:
```KAPACITOR_INFLUXDB_0_URLS_0=http://localhost:9000 kapacitord config```
should now produce a config which does the expected thing.

apply env to array elements

---

CHANGELOG.md
http_out.go
integrations/streamer_test.go
pipeline/http_out.go
services/httpd/handler.go

httpout node chains

---

integrations/benchmark_test.go

The write requests didn't returned 204,
It returned an error - "unable to parse: .."
It should answer questions in: #394 #360

Fixing benchmarks - in points creation, adding forgotten new line

---

alert.go
integrations/benchmark_test.go

Hi,
I added benchmarks for alert node and found a quick performance boost,
After memory profiling, I found that we are allocating new buffer for the templates of id,message and details, so I wrapped this in a buffer pool, and got a performance improvement:
```
benchmark                            old ns/op       new ns/op       delta
Benchmark_T10_P500_AlertTask-4       210263431       159024737       -24.37%
Benchmark_T10_P50000_AlertTask-4     18718435131     15589249575     -16.72%
Benchmark_T1000_P500_AlertTask-4     21833771619     20820186700     -4.64%
benchmark                            old allocs     new allocs     delta
Benchmark_T10_P500_AlertTask-4       490648         467352         -4.75%
Benchmark_T10_P50000_AlertTask-4     50044467       47560324       -4.96% …
```

Buffer pooling in alert templates

---

edge.go

After a bit profiling I see that incEmitted and incCollected is still hot, I saw that defer takes most of the time, after reading a bit it looks that defer has a bit of overhead and in small functions/hot code isn't recommended (should be checked in benchmark before checking, this is not a rule)
Reference: http://lk4d4.darth.io/posts/defer/
Diff between master and this branch with defaultEdgeBufferSize = 0:
```
benchmark                              old ns/op        new ns/op        delta
Benchmark_T1000_P5000_Matches-4        10894368013      10491354400      -3.70%
Benchmark_T1000_P5000_NoMatches-4      11772957621      13642020015      +15.88%
Benchmark_T100_P5000_Matches-4         1149160968       773756805        -32.67%
Benchmark_T100_P5000_NoMatches-4       1193448589 …
```

Removing defer in hot code - incCollected and incEmitted

---

CHANGELOG.md
batch.go
eval.go
expvar/expvar.go
join.go
models/batch.go
node.go
pipeline/batch.go
pipeline/eval.go
query.go
tick/eval.go
timer/timer.go

Several fixes to make batch queries work better as CQ operations

---

CHANGELOG.md
integrations/batcher_test.go
pipeline/alert.go
pipeline/batch.go

Now with the new syntax and special cases this is now a valid TICKscript.
```javascript
batch
|query('''
SELECT mean("value")
FROM "telegraf"."default".cpu_usage_idle
WHERE "host" = 'serverA' AND "cpu" != 'cpu-total'
''')
.period(10s)
.every(10s)
.groupBy(time(2s), 'cpu')
|groupBy()
|max('mean')
|httpOut('TestBatch_SimpleMR')
```

Update BatchNode to allow double GroupBy

---

CHANGELOG.md
services/replay/service.go
task.go
task_master.go

Hi,
This pull request greatly improves performance on the write benchmarks.
I did this performance improvements, in 5 steps:
_All of benchmark ran on my Macbook Pro (13-inch, Late 2011) with Intel Core i5 (2.4Ghz), 8gb memory and 120gb SSD_
To the fork struct I added measurements map from string to bool and compared it in the forkPoint.
And got the next improvement:
```
benchmark                                            old ns/op      new ns/op      delta
Benchmark_Write_MeasurementNameNotMatches_1000-4     8633314476     57042          -100.00%
Benchmark_Write_MeasurementNameMatches_1000-4        7915678886     8229547562     +3.97%
Benchmark_Write_MeasurementNameNotMatches_100-4      37434          22472          -39.97%
Benchmark_Write_MeasurementNameMatches_100-4         38474 …
```

Fork by measurement

---

tick/eval.go
tick/lex.go
tick/node.go
tick/parser.go
tick/stateful_expr.go
tick/stateful_expr_test.go

* Test cases
* BinaryNode{ NumberNode, NumberNode }, BinaryNode{ ReferenceNode, NumberNode }
* BinaryNode{ BoolNode, BoolNode }, BinaryNode{ ReferenceNode, BoolNode }
* BinaryNode{ StringNode, StringNode }, BinaryNode{ ReferenceNode, StringNode }
* BinaryNode{ StringNode, RegexNode }
* Type mismatches (comparing bool to string, int to string, etc)
* Exporting TokenType so it can be used in tests.
Caveats:
1. I didn't tested the math operator since I tested only EvalBool (I can add tests for EvalNum, if it's required).
2. I didn't know how to make the EvalBool return a ReferenceNode - @nathanielc , is this possible?

StatefulExpression: Adding tests for BinaryNode comparison operator:

---

CHANGELOG.md
integrations/data/TestStream_GroupByWhere.srpl
integrations/streamer_test.go
pipeline/stream.go

Since it is now possible to diferentiate property and chain methods in TICKscript the PR adds the ability to use both `groupBy` and `where` chain and property methods on the StreamNode.

Add chain methods `where` and `groupBy` back on stream node

---

CHANGELOG.md
tick/TICKscript.md
tick/node.go
tick/parser.go
tick/parser_test.go

Change TICKscript parser to be left-associative on equal precedence operators. 
For example previously this statement `(1+2-3*4/5)` was evaluated as `(1+(2-(3*(4/5))))` which is not the typical/expected behavior. Now using left-associative parsing the statement is evaluated as `((1+2)-((3*4)/5))`.
Fixes #429

Change TICKscript to left-associative operator precedence

---

CHANGELOG.md
alert.go
services/alerta/service.go
task_master.go

Some minor fixes to the Alerta integration...
* let the Alerta server determine the alert status otherwise alerts that have been acknowledged in the console will be incorrectly modified
* change incorrect `data` attribute to `rawData`
* default severity should be `indeterminate` otherwise automatic status changes don't work as expected

[Alerta] Do not set status, fix rawData and default severity is indeterminate

---

pipeline/node.go
pipeline/pipeline.go

With this change, more validation can be pushed from runtime to definition time.
See the current implementation of #431 for an example of how it is used.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>

Add a validate phase that allows more validation at definition time

---

build.py

This adds the full path to the `govend` call in case the `$GOPATH/bin` directory is not on the user's path.

Add path to govend call

---

CHANGELOG.md
influxql.gen.go
influxql.gen.go.tmpl
integrations/batcher_test.go
integrations/streamer_test.go
pipeline/influxql.gen.go
pipeline/influxql.gen.go.tmpl
pipeline/influxql.go

Preserve tags fields simple selector

---

CHANGELOG.md
alert.go
integrations/batcher_test.go
integrations/streamer_test.go
node.go
pipeline/alert.go
pipeline/batch.go
pipeline/node.go
pipeline/stream.go
pipeline/udf.go
tick/eval.go
tick/eval_test.go

Fixes #93 
Alert data can now be consumed directly from within TICKscripts.
For example, let's say we want to store all data that triggered an alert in InfluxDB with a tag `level` containing the level string value (i.e CRITICAL).
```javascript
...
|alert()
.warn(...)
.crit(...)
.levelTag('level')
// Or use a field
.levelField('level')
|influxDBOut()
.database('alerts')
...
```

Alert data outputs to children nodes

---

Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64
Dockerfile_build_ubuntu64_git
cmd/kapacitord/run/server_test.go
install-deps.sh

The kapacitor unit tests don't run locally unless the protobuf
dependencies are installed locally.
Since the required glue is somewhat non-trivial, factor the glue
out from the Dockerfiles and change the docker files to use the same
glue.
Add a comment to the test to indicate how to fix the missing dependencies
issue.
Signed-off-by: Jon Seymour <jon@wildducktheories.com>

Factor out the protobuf dependency into a shell script.

---

CHANGELOG.md
alert.go
integrations/batcher_test.go
pipeline/alert.go

Fixes #281 
Note the `any` method was not added as that is the default behavior.
This is now possible:
```javascript
|alert()
.all()
.warn(lamnda: "value" > 5)
.crit(lamnda: "value" > 10)
```
Given a batch of data with:
```
value 7
value 12
value 4
```
No alert would be triggered
Given a batch of data with:
```
value 7
value 12
value 6
```
A `WARNING` will be triggered
Given a batch of data with:
```
value 13
value 12
value 15
```
A `CRITICAL` will be triggered

Can now require that all points in alert batch match criteria

---

CHANGELOG.md
client/v1/client.go
client/v1/client_test.go
cmd/kapacitor/main.go
cmd/kapacitord/run/server_test.go
services/task_store/service.go

Now an optional `skip-format` query parameter is available on the `GET /task` endpoint.

Allow disabling TICKscript formatting

---

CHANGELOG.md
alert.go
integrations/batcher_test.go
integrations/data/TestStream_AlertDuration.srpl
integrations/streamer_test.go
pipeline/alert.go

Fixes #388 Adds a duration to the alert data of all triggered alerts. 
You can also store this duration by using the `.durationField` property of an AlertNode in a similar way to the  `levelField` property.
```go
|alert()
.durationField('duration')
|influxDBOut()
....
```
The data in InfluxDB will now contain a field with the key `duration` containing and int64 for the duration of the event in nanoseconds.

add duration to alert data

---

CHANGELOG.md
cmd/kapacitord/run/command.go
cmd/kapacitord/run/config_command.go

If the `-config` option isn't used, Kapacitor will now attempt to read a
configuration file from the environment variable `KAPACITOR_CONFIG_PATH`
or a list of default locations.
The list of default locations:
* `~/.kapacitor/kapacitor.conf`
* `/etc/kapacitor/kapacitor.conf`

Default config file location

---

tick/stateful_expr_benchmarks_test.go

Current results
```
PASS
Benchmark_EvalBool_OneOperator_NumberFloat64_NumberFloat64-4                      	 3000000	       543 ns/op	      72 B/op	       5 allocs/op
Benchmark_EvalBool_OneOperator_NumberFloat64_NumberInt64-4                        	 3000000	       554 ns/op	      72 B/op	       5 allocs/op
Benchmark_EvalBool_OneOperator_NumberInt64_NumberInt64-4                          	 3000000	       551 ns/op	      72 B/op	       5 allocs/op
Benchmark_EvalBool_OneOperator_ReferenceNodeFloat64_NumberFloat64-4               	 3000000	       530 ns/op	      64 B/op	       4 allocs/op
Benchmark_EvalBool_OneOperator_ReferenceNodeFloat64_NumberInt64-4                 	 3000000	       522 ns/op	      64 B/op	       4 allocs/op
Benchmark_EvalBool_OneOperator_ReferenceNodeFloat64_ReferenceNode …
```

Adding benchmark for stateful expression

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go

Make the Alerta event property configurable to ensure [de-duplication](http://docs.alerta.io/en/latest/server.html#de-duplication) and [event correlation](http://docs.alerta.io/en/latest/server.html#simple-correlation) work as expected.

Make Alerta event property configurable

---

build.py
circle.yml
test.sh

With this PR:
- Minor overall updates to build script
- Changes non-release versioning scheme to `<version>~<branch>.<commit>`
- Circle build artifacts are now uploaded to S3
- Changes default upload bucket to `dl.influxdata.com/kapacitor/artifacts` for circle build artifacts and `dl.influxdata.com/kapacitor/releases` for releases
- Package iteration is now removed from output package names (for example, `0.12.2-1` displays as `0.12.2`), however the iteration is still included in the package metadata.

Minor build script improvements, upload artifacts

---

client/API.md
client/v1/swagger.yml

Up until this point the Kapacitor HTTP API has been "implemented" rather than "designed". This PR presents an API "design" in the form of documentation, in preparation for locking down the API to a more supportable long lived API.
Currently the existing API has some inconsistencies and odd usage patterns. This doc attempts to unify and simplify using the API. It makes the API more RESTful and consistent with itself.
For the most part only small changes where made to the existing API. For example when query parameters vs JSON structures vs path elements are used is clear and consistent. Parameter names and top level keys in JSON structures all use lower case names. 
This represents  a breaking change to the API. It is intended that once we settle on this API design that it will not need …

Proposed HTTP API Changes

---

build.py

This PR:
- Removes the `--rc` flag. From now on specify RC in version tag (ex: `0.13.0-rc1`).
- Fixes issue for tarball filesystem hierarchy.
- Fix issue when using `--name` flag
- Converts any dashes or underscores in version information to tildes
/cc @nathanielc

Minor build fixes

---

CHANGELOG.md
integrations/data/TestStream_JoinTolerance.srpl
integrations/streamer_test.go
join.go

This improves the JoinNode by removing some of the latency introduced. The JoinNode will now emit joined sets as soon as they are full.
This may fix #374 as the join node could have buffered a join set per group, causing delayed alerts.

Join can emit ready sets without waiting

---

alert.go
eval.go
expr.go
stream.go
tick/stateful/expr.go
tick/stateful/scope_pool.go
tick/stateful/scope_pool_test.go
where.go

**This pull request, is experiment, If you like the idea, we can improve the readability and the quality of the code**
For each expression we are creating "scope pool", which is object pool of scopes - with some extra magic.
By doing quick analysis on the node AST I know which tags and fields he requires. so we put only the required ones.
For example: "value" > 10, I fill only "value" from field or tag.
```
name                     old time/op    new time/op    delta
_T10_P500_AlertTask-4       133ms ± 4%     123ms ± 4%   -7.58%  (p=0.008 n=5+5)
_T10_P50000_AlertTask-4     13.4s ± 8%     12.3s ± 7%     ~     (p=0.056 n=5+5)
_T1000_P500_AlertTask-4     13.5s ± 4%     12.1s ± 3%  -10.46%  (p=0.008 n=5+5)
name                     old alloc/op   new alloc/op   delta
_T10_P500_AlertTask-4 …
```

Scope reusing & smaller scopes

---

eval.go
expr.go
tick/stateful/eval_reference_node.go
tick/stateful/expr_test.go
tick/stateful/types.go

Since using `ScopePool` all scope values are always set. As a result the EvalReferenceNode would return `nil` values instead of an error. Now we check for `nil` values and return appropriate error.

Fix panic when missing value in scope

---

CHANGELOG.md
alert.go
batch.go
default.go
eval.go
influxdb_out.go
pipeline/alert.go
pipeline/batch.go
pipeline/default.go
pipeline/eval.go
pipeline/influxdb_out.go

Update nodes to provide useful stats.
Fixes #419

Update node stats

---

CHANGELOG.md
client/API.md
cmd/kapacitord/run/server_test.go
services/httpd/handler.go
services/replay/service.go
services/task_store/service.go

Fixes #543 #544 #545 
As for #544 all IDs (tasks, recordings, replays) must match this regex `^[-\._\p{L}0-9]+$`, which is essentially numbers, unicode letters, '-', '.' and '_'.
If you have existing tasks which do not match this pattern they should continue to function normally with this fix.

Fixes several issues with the API

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
services/pagerduty/service.go
task_master.go

Resolves issue #82, should work like VictorOps integration, if you do not specify a service key, the default service key from the configuration file is used. If you do include a service key, it is used instead of the default.

Add optional .serviceKey('XXX') argument to pagerduty alerts.

---

CHANGELOG.md
influxql.gen.go
influxql.gen.go.tmpl
integrations/data/TestStream_Selectors.srpl
integrations/streamer_test.go

This finishes up the work to preserve fields along with tags.
The selected field will be renamed as per normal operations. i.e
```
|last('mean')
.as('last_mean')
```
The mean field will be renamed to last_mean and all other fields will remain the same.

Preserve fields in selectors as well as tags

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/client_test.go
client/v1/swagger.yml
cmd/kapacitor/main.go
cmd/kapacitord/run/server_test.go
integrations/batcher_test.go
integrations/streamer_test.go
replay.go
services/replay/service.go
services/task_store/service.go

Fixes #283 
Now via the API and the CLI you can replay data against a task without having to first create a recording.
Basically the record and replay commands were into a new command with the capabilities of both. 
See the CLI help or API docs for more details.
TODO:

Add live replays

---

CHANGELOG.md
tick/lex.go
tick/stateful/eval_binary_node.go
tick/stateful/eval_function_node_test.go
tick/stateful/evaluation_funcs.go
tick/stateful/expr_dynamic_test.go
tick/stateful/expr_test.go
tick/stateful/types.go

Fixes #561 
Changes the error detection to compile time if possible.
Also refactors the `invalid ... operator` errors to be left/right symmetric and correctly report Regex errors.

Fix issue with nested binary operators counting as constant typed

---

CHANGELOG.md
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
services/httpd/config.go
services/influxdb/config.go
services/influxdb/service.go
services/task_store/service.go

This PR depends on https://github.com/influxdata/influxdb/pull/6655
TODO:

Support HTTP based subscriptions

---

integrations/batcher_test.go
query.go

Explicitly validate that a batch query is a single select statement.

Validate single select statement.

---

CHANGELOG.md
client/v1/client.go
cmd/kapacitor/main.go
cmd/kapacitord/run/server.go
expvar/expvar.go
integrations/batcher_test.go
integrations/benchmark_test.go
integrations/streamer_test.go
node.go
services/replay/service.go
task_master.go

Track ingress stats. Fixes #416
Kapacitor now counts all points received independent of a task listening for the data.
This helps debug issues with Kapacitor subscriptions etc.
There are three ways to access these stats:
1. Via the API at /debug/vars
2. Via the `_kapacitor` internal db
3. Via the cli  `kapacitor stats ingress`
>NOTE: Since there can be multiple task_masters internal to Kapacitor for recordings/replays etc, the stats tagged with `task_master=main` are the stats for normal operation.

Track ingress stats

---

CHANGELOG.md
pipeline/influxql.go
vendor.yml
vendor/github.com/dustin/go-humanize/README.markdown
vendor/github.com/dustin/go-humanize/commaf.go
vendor/github.com/influxdata/influxdb/influxql/functions.go
vendor/github.com/influxdata/influxdb/influxql/iterator.go
vendor/github.com/influxdata/influxdb/influxql/neldermead/neldermead.go
vendor/github.com/influxdata/influxdb/influxql/select.go
vendor/github.com/twinj/uuid/README.md
vendor/github.com/twinj/uuid/appveyor.yml

Add Holt Winters InfluxQL function
For example one can now define an alert based off forecasted future values.
The following TICKscript will take the last 30 days of disk usage stats and using holt-winters forecast the next 7 days. If the forecasted value crosses a threshold an alert is triggered.
The result is now Kapacitor will alert you 7 days in advance of a disk filling up. This assumes a slow growth but by changing the vars in the script you could check for shorter growth intervals.
```go
// The interval on which to aggregate the disk usage
var agg_interval = 1d
// The number of `agg_interval`s to forecast into the future
var forecast_count = 7
// The amount of historical data to use for the fit
var history = 30d
// The critical threshold on used_percent
var threshold = 90.0
batch …
```

Add HoltWinters method

---

CHANGELOG.md
edge.go

So there are several stats that Kapacitor keeps track of, and they have different uses. 
1. Every edge has an emitted/collected counters.  These are the stats printed in the `kapacitor show ` command under processed.
2. Every edge has emitted/collected counters for each group of the source node. These are the stats used for deadman's switch aka the StatsNode.
Depending on the edge type the counters count different things.
For Stream edges its simple. The counters always count the number of points emitted or collected.
For batch its different. You can count the number of batches or the number of points in each batch. Both counts are important as such this PR changes the behavior so we can capture both values.
Above first counters count the number of batches the edge has processed. The …

update batch group stats to be by len(b.Points)

---

CHANGELOG.md
build.py
cmd/kapacitor/main.go
etc/bash_completion.d/kapacitor.sh
usr/share/bash-completion/completions/kapacitor

Adds bash completion to the `kapacitor` cli command.

Add bash completetion, fix a few oddities with the cli

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/client_test.go
client/v1/swagger.yml
cmd/kapacitor/main.go
cmd/kapacitord/run/server_test.go
services/task_store/dao.go
services/task_store/service.go

Fixes #613 
A small breaking change to the API was introduced where the PATCH requests new return the complete object definition instead of a 204. This allows for the client to update its link if the ID changed.

Allow Task and Template IDs to be modified

---

CHANGELOG.md
cmd/kapacitord/run/server.go
cmd/kapacitord/run/server_helper_test.go
integrations/benchmark_test.go
integrations/helpers_test.go
integrations/streamer_test.go
services/httpd/handler.go
services/httpd/logger.go
services/httpd/service.go
services/logging/service.go

Use CLF for http logs

---

CHANGELOG.md
cmd/kapacitord/run/server_helper_test.go
cmd/kapacitord/run/server_test.go
services/task_store/service.go

Fixes #626 where after changing a task ID `kapacitor show` would be inaccurate.
Changing a task ID would leave the original task running under the original name so `kapacitor show` with the new name would report that the task was not running since it couldn't find it.
Now the task is stopped and started again under the new name.

Fix #626, fixes issues with changing task/template IDs

---

CHANGELOG.md
services/udf/service.go
udf.go
udf/agent/agent.go
udf/agent/py/agent.py

Now when using a socket UDF the write and read ends of the socket are closed separately so they can cause error for each other.

Fixes issues with socket UDFs getting a read error

---

pipeline/node.go

Mistake in documentation - should 10s.
Fix for https://github.com/influxdata/kapacitor/issues/640

[#640] Fixed documentation for deadman

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/swagger.yml
cmd/kapacitor/main.go
cmd/kapacitord/run/server.go
influxql.go
services/replay/service.go
services/task_store/service.go
task_master.go
usr/share/bash-completion/completions/kapacitor

Now you can do this:
```
$ kapacitor replay -recording recordingID -task taskID -no-wait
REPLAY_ID
$ kapacitor show -replay REPLAY_ID taskID
....
```
The show output is now in context of the task running for the replay, not the normal task. This way you can watch a task execute within a replay.

Add optional to be able to show a task in the context of a replay

---

CHANGELOG.md
alert.go
cmd/kapacitord/run/config.go
cmd/kapacitord/run/server.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
services/telegram/config.go
services/telegram/service.go
task_master.go

Telegram Alerting

---

CHANGELOG.md
integrations/batcher_test.go
integrations/streamer_test.go
join.go
pipeline/join.go

This addresses the issues with customizing the delimiter for the Join operation, by directly allowing you to customize it.

Add delimit option to JoinNode

---

CHANGELOG.md
tick/ast/lex.go

Detect unterminated regex when EOF reached

---

CHANGELOG.md
replay.go

Fixes #719, this is the fix for the panic only. We need a better way to represent the tmax of a batch in the batch recording files.

Fix panic in replay

---

pipeline/alert.go

The missing dot causes the generated doc to include a confusing sentence:

Fix missing dot causes confusing sentence in AlertNode doc

---

CHANGELOG.md
alert.go
pipeline/alert.go

Fixes #298
@beckettsean @rkuchan In reference to this blog post: https://influxdata.com/blog/tldr-influxdb-tech-tips-may-19-2016/ about Alert levels begin subsets. I think it should change, and this PR makes the change so that each alert level is independent of other levels.
Some of my reasons:
* It's initially confusing, since its natural to think in the context of only a single alert level when writing the expression.
* It's become really painful when your data does not follow a continuous domain (aka the data is not sort-able like a set of strings as labels). 
Example of non continuous data:
```
// Data has status flag with values OK, WARN, or CRITICAL
// You have to write the expressions as
|alert()
.warn(lambda: "status" == 'WARN' OR "status" == 'CRITICAL')
.crit(lambda: "status" == …
```

Change alert levels to be independent

---

CHANGELOG.md
pipeline/pipeline.go
task_master.go

Fixes #749. There is still the possibility of disabling a task hanging and keeping the lock but this fill will prevent this edge case.

Disallow empty tasks

---

CHANGELOG.md
expr.go
pipeline/node.go
tick/stateful/expr.go

Fixes #718 
We need to add tests for this but its not easy until the deadman can have its own clock. I'll create an issue to track this. #754

Fix broken deadman extra expressions

---

CHANGELOG.md
auth/auth.go
server/server.go
services/httpd/handler.go
services/influxdb/service.go
services/noauth/service.go

Add method for authenticating subscriptions.

---

auth/auth.go
services/httpd/handler.go
services/influxdb/service.go
services/noauth/service.go

Changes the subscription auth to use Basic Auth instead of custom headers and such.

Use BasicAuth + special user for subscriptions instead of custom headers

---

CHANGELOG.md
tick/stateful/functions.go
tick/stateful/functions_test.go

Adding "if" function to tick

---

CHANGELOG.md
services/task_store/dao.go
services/task_store/service.go

Delete snaphost when task is deleted

---

README.md
examples/telegraf/README.md
examples/telegraf/cpu/cpu_alert_batch.tick
examples/telegraf/cpu/cpu_alert_stream.tick
examples/telegraf/disk/disk_alert_batch.tick
examples/telegraf/disk/disk_alert_stream.tick
examples/telegraf/generic_batch_example.tick
examples/telegraf/generic_stream_example.tick
examples/telegraf/mem/mem_alert_batch.tick
examples/telegraf/mem/mem_alert_stream.tick
examples/telegraf/net/net_alert_batch.tick
examples/telegraf/net/net_alert_stream.tick
examples/telegraf/net/net_udp_buffer_overflow_alert.tick
examples/telegraf/netstat/netstat_alert_batch.tick
examples/telegraf/netstat/netstat_alert_stream.tick

This is a start on providing standardized tickscripts for each telegraf plugin. I have included a README for the standard format and will be opening a PR on /telegraf/CONTRIBUTING.md to nudge contributors into write tickscripts for their telegraf plugins.

Tickscripts for Telegraf

---

CHANGELOG.md
server/server.go
services/influxdb/service.go

This fixes some subscription linking bugs as well as adds an API endpoint to trigger a linking event.
The fixes:
* Subscriptions will be recreated if they were manually deleted.
* UDP listen ports will be closed if a database is dropped.

Add API endpoint to refresh subscriptions 

---

pipeline/window.go

ports https://github.com/influxdata/docs.influxdata.com/pull/624 changes to Kapacitor docs source.

moving docs #624 to kap

---

CHANGELOG.md
alert.go
pipeline/alert.go

Add TCP alert handler

---

CHANGELOG.md
tick/stateful/evaluation_funcs.go
tick/stateful/expr_test.go

Allow duration / duration in TICKscript

---

CHANGELOG.md
log.go

The previous output of `|log()` node in TICKscript was the Go representation of the struct, which required that you know both the field names and order to understand. 
This switches the output to JSON, its more verbose and as a result self documenting.

Improve log readability by using json log output

---

CHANGELOG.md
batch.go
influxql.gen.go
influxql.gen.go.tmpl
query.go
replay.go
services/replay/service.go
task.go

TMax for a batch edge was incorrectly set for Holt-Winters methods. This corrects the issue.

Fix issues with holt winters and tmax

---

CHANGELOG.md
batch.go
query.go
query_test.go
server/server_test.go
services/replay/service.go

Fixes issues where setting TMax on a batch result and grouping by time did the wrong thing.
Now the TMax is not set to the query bounds if you are grouping by time. TMax is set to the query bounds in for non group by time queries and empty results.

Set tmax if the batch is empty or not grouping by time

---

CHANGELOG.md
tick/ast/lex.go
tick/ast/lex_test.go
tick/ast/parser.go
tick/ast/parser_test.go
tick/stateful/functions.go
tick/stateful/functions_test.go

Fixes #777 
There are three major changes in this PR:
1. Add a set of functions to the lambda expressions for string manipulation
2. Update the lexer/parser to allow for regex literals to be function arguments, (this was needed for one of the string manipulation functions).
3. Convert all stateless function objects to value receivers.

Add string manipulation functions

---

CHANGELOG.md
server/server.go

Reverts influxdata/kapacitor#949

Revert "Fail startup when we fail to save the cluster/server IDs"

---

CHANGELOG.md
Dockerfile_build_ubuntu32
Dockerfile_build_ubuntu64
server/server_test.go
test.sh

Update to go1.7

---

CHANGELOG.md
eval.go
integrations/data/TestStream_Eval_KeepSome.srpl
integrations/streamer_test.go

Fixes #984 
Update the eval node to check for fields in the original fields list in addition to any newly computed fields.

Eval.Keep now works with non referenced vars

---

k8s_autoscale.go
pipeline/k8s_autoscale.go
services/k8s/client/types.go

ReplicaSets can also be scaled like Deployments and ReplicationControllers.
Counts all errors instead of only API related errors.

Add support for scaling replicasets too

---

CHANGELOG.md
cmd/kapacitor/main.go

Fixes #785 
Having inconsistent sorting and ID that ran over columns is painful. This simple change fixes both of those issues.
Not that the recordings/replays did not get the sorting change since they are naturally sorted by time in the API.

Sort and dynamically adjust column widths in CLI output

---

CHANGELOG.md
tick/stateful/functions.go
tick/stateful/functions_test.go

The strings functions was missing a way to get the length of a string. It has now been added.

Add missing strLength function

---

client/API.md
client/v1/client.go
client/v1/client_test.go
server/server_test.go
services/config/override/override.go
services/config/override/override_test.go
services/config/service.go
services/config/service_test.go

Updates the Config API endpoint to return a list of redacted options. This way a consumer can know which options have been redacted and behave accordingly.

Return list of redacted options in config API endpoints

---

CHANGELOG.md
integrations/data/TestStream_Window.srpl
integrations/streamer_test.go
pipeline/window.go
window.go

Fixes #898 
With this change, the window node can emit points immediately without having to wait for the next point when the every value is zero.
The original behavior was that the window would be emitted for each new point, but the emitted window lagged behind the current point. In other words to output of the window node does not change, but an optimization has been added to emit the window sooner.

Fix window node so that when every==0, we can immediately emit the current window

---

CHANGELOG.md
integrations/streamer_test.go
server/server_test.go
services/alerta/config.go
services/alerta/service.go

Resolves issue #1052 
I have tested this change live with the custom kapacitor docker image allen13/kapacitor:latest

Move alerta api token to header and add option to skip TLS verification.

---

udf/agent/examples/outliers/outliers.py

The outliers UDF has no need for an `as` property as it is essentially a filtering node and outputs the input points, that were outliers,  unmodified.

Remove dead code for the `as` property on the outliers example UDF

---

integrations/streamer_test.go
services/alerta/service.go

- [X ] Rebased/mergable
- [ X] Tests pass
- [ X] CHANGELOG.md updated
- [ X] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
This address the alerta token failure reported here https://github.com/influxdata/kapacitor/issues/1076

Change alerta auth token prefix from Bearer to Key.

---

CHANGELOG.md
integrations/streamer_test.go
services/slack/service.go

Enable markdown in slack attachments #251

---

CHANGELOG.md
integrations/data/TestStream_Union_Stepped.srpl
integrations/streamer_test.go
test.sh
union.go

The union node was caching points for too long. This change makes it so that the union node emits points as soon as possible. 
Writing a test for this has been a bit challenging as the change in behavior is only related to the timing of emits, and cannot be easily tested with the existing integration tests.
I have put together a hacky test for now to demonstrate its working, but it probably shouldn't be merged in this state.
The ideal way to test this would be either: clean up the `ExecutingTask` code such that it is easier to setup a single node in isolation, or enhance the edge communication so it can carry metadata messages as well and add `barrier` messages. The reality is both probably need to happen.
Fixes #1100

Update union node

---

CHANGELOG.md
batch.go
pipeline/batch.go
query.go
query_test.go

Allow QueryNodes to automatically align GROUP BY time intervals to the start time for each query sent to influx.  This leverages the offset argument to `GROUP BY time()` to offset directly to the start time.

Add new query property for aligning group by intervals to start times

---

CHANGELOG.md
services/influxdb/service.go

The second stack trace reported in #1087 is caused by closing the `influxdbCluster` type after it has failed to open. This PR fixes the issue

Fix panic on closing failed to open influxdbCluster type

---

CHANGELOG.md
server/server_test.go
services/httpd/handler.go

Fix pprof endpoint

---

CHANGELOG.md
services/config/service.go
services/config/service_test.go

This fixes a flaky test. Add defensive measures to handleUpdateSection code, increases timeout in test.
Now if the timeout is reached in the test the test will fail immediately instead of hanging and waiting for the longer test timeout.

Fix hang in config API if update failed or takes too long

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
server/server_test.go
services/alerta/config.go
services/alerta/service.go

Addresses this issue: https://github.com/influxdata/kapacitor/issues/1165

Make the alerta auth token prefix configurable and default it to Bearer.

---

etc/kapacitor/kapacitor.conf

Remove http auth option from default configuration

---

CHANGELOG.md
etc/logrotate.d/kapacitor

The logrotate execution won't work because the proper name of the error log is `kapacitord.err`.

Fix name of kapacitor error log in log rotate file

---

CHANGELOG.md
services/telegram/service.go

This PR fixes the case-sensitivity of Telegram `parseMode` values. This is done by lower-casing those values before validation.
I don't know where and how to test this, so I left that out of this PR. Let me know if this is required and how I can add them.
Fixes #1133

Fix case-sensitivity of Telegram parse mode values.

---

CHANGELOG.md
alert.go
server/server_test.go

With the new restoring of alert state there was a bug where the alert duration would be incorrect.

Fix bug where duration of alert was incorrect when restoring alert state

---

cmd/kapacitor/main.go

Previously the dbrp values that contained quotes would fail to parse. This PR fixes that issue.
See #1166

Fix dbrp parsing so quoted dbrp values can be parsed correctly

---

services/logging/loggingtest/logging.go

Small change the the loggingtest package to make testing multple servers at once easier.

Add prefix feature to loggingtest service

---

CHANGELOG.md
alert.go
batch.go
combine.go
derivative.go
eval.go
flatten.go
influxdb_out.go
influxql.go
join.go
k8s_autoscale.go
log.go
node.go
server/server_test.go
stream.go
where.go

Add error counters to every node type

---

CHANGELOG.md
services/replay/service.go

Adding a check, if the filenames inside the replay folder contain an extension, otherwise, Kapacitor will panic on startup.
Seems to be a trivial PR.

check if replay file has an extension

---

pipeline/influxql.go

Links the Kapacitor's Holt-Winters documentation to InfluxDB's Holt-Winters documentation for users looking to learn about the function.
Attempts to fix this docs issue asking for more detail about Holt-Winters in the Kapacitor docs: https://github.com/influxdata/docs.influxdata.com/issues/1039.

Add link to InfluxDB Holt-Winters documentation

---

pipeline/alert.go

Adds a link to the event handler setup guide created in https://github.com/influxdata/docs.influxdata.com/pull/996. So far, this is only for HipChat and Telegram.

Add link to event handler setup guide for telegram and hipchat

---

CHANGELOG.md
alert.go
combine.go
derivative.go
eval.go
expvar/expvar.go
flatten.go
group_by.go
http_out.go
influxql.go
integrations/data/TestStream_Cardinality.srpl
integrations/streamer_test.go
join.go
k8s_autoscale.go
node.go
sample.go
server/server_test.go
where.go
window.go

This PR introduces a new stat `cardinality` that tracks the number of groups that exist for a given node for each relevant node type.

WIP: Add cardinality stat to each node type.

---

CHANGELOG.md
integrations/batcher_test.go
integrations/data/TestBatch_StateTracking.0.brpl
integrations/data/TestStream_StateTracking.srpl
integrations/streamer_test.go
pipeline/node.go
pipeline/state_tracking.go
state_tracking.go
task.go

This is a proposal for a solution to #1211 
It provides a node which evaluates an expression, and adds a field which tracks how long the expression has evaluated as true.
Example usage which alerts when a host has not had any primary ntp peers for over 5 minutes looks like:
```
stream
|from().measurement('ntpq')|default().tag('state_prefix',' ')
|groupBy('host')
|stateDuration(lambda: "state_prefix" != '*').unit(1m)
|alert()
.warn(lambda: "state_duration" > 5)
.crit(lambda: "state_duration" > 60)
```
If this is an acceptable solution to the problem, I can finish up the PR by adding tests, docs, etc.
Closes #1211 #1225

add StateDuration node

---

examples/telegraf/cpu/cpu_alert_batch.tick
examples/telegraf/cpu/cpu_alert_stream.tick
examples/telegraf/disk/disk_alert_batch.tick
examples/telegraf/disk/disk_alert_stream.tick

Hey Folks,
I've discovered some minor issues with your examples and wanted to share my experiences:
1. The cpu example is only alerting when `usage_user` exceeds the thresholds. Problems like high IOWait or System usage are not alerted. It should check the threshold against everything that is **not idle**.
2. The disk example checks the threshold agains the `mean` of **all disks available**. This means if one disk is full but another one almost empty, there is no alert. It should group by path and then alert with the path as well.
Cheers,
Christian

Example TICKScript improvements

---

server/server_test.go
services/config/service_test.go

Fixes #1307
There was a race in the config service test which has been removed.
The SNMPTrap test would drop UDP packets on occasion. I have increased the retry count for the test.

Fix two flaky tests

---

CHANGELOG.md
influxql.gen.go
influxql.gen.go.tmpl
influxql.go
integrations/data/TestStream_Aggregate_Changing_Type.srpl
integrations/streamer_test.go
pipeline/influxql.go
tmpldata.json

Fix bug where aggregate operations could not change type

---

CHANGELOG.md
influxdb/client.go

Fix for InfluxDB client not updating if the client credentials have changed.

Update client if credentials have changed

---

CHANGELOG.md
alert.go
pipeline/alert.go
server/server_test.go
services/alert/service.go
services/sensu/service.go
task_master.go

adding source for sensu alert as parameter

---

services/scraper/config.go

Scraper timeout was not being sent along to underlying scraper.

Fix scraper timeout not being used

---

CHANGELOG.md
models/batch.go
server/server_test.go
services/replay/service.go

Fixes #1294 , @hraftery do you have the ability to build and test out this PR to confirm it fixes your issue?

Fix batch queries missing all fields after the first nil field

---

CHANGELOG.md
alert.go
alert/types.go
etc/kapacitor/kapacitor.conf
http_post.go
integrations/batcher_test.go
integrations/helpers_test.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/http_post.go
pipeline/node.go
server/config.go
server/config_test.go
server/server.go
server/server_test.go
services/alert/alerttest/alerttest.go
services/alert/handlers.go
services/alert/service.go
services/config/override/doc.go
services/config/override/override.go
services/config/override/override_internal_test.go
services/httppost/config.go
services/httppost/httpposttest/server.go
services/httppost/service.go
task_master.go

This PR allows users to create POST request `endpoints` for an alert node where arbitrary HTTP headers may be set. It works as a fix for https://github.com/influxdata/kapacitor/issues/117.
Todo:

WIP: Add httppost service (add headers to POST alerts)

---

CHANGELOG.md
alert.go
pipeline/alert.go
server/server_test.go
services/sensu/config.go
services/sensu/service.go

allowing sensu handler to be specified

---

CHANGELOG.md
client/v1/client.go
influxdb/client.go
services/alerta/service.go
services/influxdb/service.go
services/k8s/client/client.go

Most services and clients throughout Kapacitor use the Default HTTP
Client which uses the Default HTTP Transport, which uses HTTP proxies as
directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy)
environment variables.
For the services that use a custom Transport, we use
http.ProxyFromEnvironment.
The downside to this is that all future implementers will need to copy
this pattern
Fixes #841 (though its not conditional proxy as the issue has requested)

Use ProxyFromEnvironment for all HTTP Transport where needed

---

CHANGELOG.md
flatten.go
group_by.go
integrations/data/TestStream_BatchGroupBy.srpl
integrations/data/TestStream_GroupByExclude.srpl
integrations/streamer_test.go
pipeline/flatten.go
pipeline/group_by.go
pipeline/stream.go
stream.go

Add the ability to exclude certain tags when grouping by *
Add a drop original field name to the flatten node.

Add groupBy exclude, Add dropOriginalFieldName to flatten

---

CHANGELOG.md
integrations/data/TestStream_KapacitorLoopback.srpl
integrations/streamer_test.go
kapacitor_loopback.go
pipeline/influxdb_out.go
pipeline/kapacitor_loopback.go
pipeline/node.go
task.go
task_master.go

Adds the ability to natively emit data back into Kapacitor from a task
Does this break the order guarantee? No, not anymore than you could have done using InfluxDBOut.
We can always gate loopback writes through a reorder step if it does become something that is hard to manage in practice.
Does this allow creation of infinite loops? Yes, but not within the same task. To create an infinite loop you would need to use at least two task each with a loopback pointing at the other. A warning has been added to the docs, but this should be rare.

Add kapacitor loopback

---

integrations/batcher_test.go
integrations/streamer_test.go
state_tracking.go

This fixes the map write race condition reported in https://github.com/influxdata/kapacitor/issues/1369#issuecomment-301778741 as well as the point sharing issue reported in #1379, but only for stateDuration & stateCount. If this is the solution we want to go with (copying the batch), I can implement on the other nodes.

fix stateDuration & stateCount adding fields to wrong point in batch

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
services/static_discovery/config.go
services/static_discovery/config_test.go

The static-discovery configuration was difficult to use:
Previously, it had a prometheus assumption of `__address__` as a target:
```toml
[[static-discovery]]
enabled = true
id = "mystatic"
targets = [{ "__address__" = "localhost:9100"}]
[static.labels]
region = "us-east-1"
```
The `static-discovery` configuration section has been simplified to look like this:
```toml
[[static-discovery]]
enabled = true
id = "mystatic"
targets = ["localhost:9100"]
[static.labels]
region = "us-east-1"
```

Update static-discovery config to supply __address__

---

CHANGELOG.md
default.go
delete.go
derivative.go
eval.go
models/batch.go
shift.go
state_tracking.go

Fixes #1379 
The idea of this change is to shallow copy the batch points slice so that nodes which modify the batch points slice do not collide.
The existing code already takes care to copy the maps before modification, but that didn't matter since the underlying slice was shared. This change copies the slice to prevent those issues.
This is horrible :), I really dislike how this came together and we need a better way to manage copying/modifying data. My hope is that the migration to message passing #1319 will open up a way to manage this better. There is simply too much onus on each implementation of a node to keep everything straight and not introduce new bugs.

Copy batch points slice before modification

---

CHANGELOG.md
services/scraper/service.go

If an Append happened at the same time as a Commit of a configuration change it was possible to deadlock the scraper.
Update the Scraper config to be atomic.  This implies that the configuration is on a different lifecycle than the Append.

Fix deadlock if Append happens at same time as Commit

---

CHANGELOG.md
services/scraper/config.go
services/scraper/service.go

Problem:
Raw scrape data from Prometheus targets was all in a single measurement and essentially unusable as a result.  Currently you must use some kind of TICKscript to transform the data to something more usable.
Solution:
Use the `__name__` tag as the measurement name, but leave the `__name__` tag on the raw data. This allows for transformations to be easily made if desired and for the default raw data to more accessible.

Use the Prometheus metric name as the measurement name by default.

---

CHANGELOG.md
pipeline/k8s_autoscale.go
server/config.go

Env vars like `KAPACITOR_KUBERNETES_..` previously worked but currently do not.
Since the Kubernetes config section can be both a single section or a list of sections we have added support for implict 0 indexes in the env var names. This new behavior must be explicitly enabled for each configuration section that needs it. Currently on the kubernetes section needs this change.

Fix bug where env overrides stopped working for the k8s config section

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf

Using ENV var to override configuration only works for slices if there is already a entry in the slice.
This changes the default configuration to include an entry for each section. Each entry still default to being disabled which makes it equivalent with the exception that ENV vars can now be used to enabled and otherwise manipulate the default entry.

Update example config to have default discoverer sections that are disabled

---

CHANGELOG.md
services/httpd/service.go

Add http server error logger

---

tick/stateful/functions.go

This PR introduces the ability to convert timestamps to integers. The purpose of this is to allow users to perform mathematical operations using the timestamp.

WIP: Add built in functions to convert timestamps to integers

---

CHANGELOG.md
tick/ast/node.go
tick/stateful/eval_binary_node.go
tick/stateful/eval_bool_node.go
tick/stateful/eval_duration_node.go
tick/stateful/eval_float_node.go
tick/stateful/eval_function_node.go
tick/stateful/eval_int_node.go
tick/stateful/eval_lambda_node.go
tick/stateful/eval_reference_node.go
tick/stateful/eval_regex_node.go
tick/stateful/eval_string_node.go
tick/stateful/eval_unary_node.go
tick/stateful/functions.go
tick/stateful/node_evaluator.go
tick/stateful/scope.go

Fixes #1452 
Log line now reads like
```
[missing:where2] 2017/07/07 11:05:08 E! error while evaluating expression: Cannot call function "sigma" with args ("y": missing), available signatures are [(float)].
```

Fix unhelpful error message for node evaluators

---

integrations/streamer_test.go
server/server_test.go
services/pagerduty/service.go

Fixes #743 
Previously the details field specified on an alert node was not being used in the pagerduty service. Instead, the results object that generated was being used. This PR now uses the details field specified.
@nathanielc is this all, or is there something I'm missing?

Use details field from alert node in pagerduty

---

CHANGELOG.md
integrations/streamer_test.go

I'm surprised that the tests were passing in the first place.

Fix pagerduty test that required server info

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
server/server_test.go
services/alerta/alertatest/alertatest.go
services/alerta/config.go
services/alerta/service.go

Add template support to service field as requested in #1543
Add timeout support as requested in #1264 
Add tags support as requested in #1546

Alerta support for timeout, tags and service template

---

CHANGELOG.md
server/server_const_test.go
server/server_const_windows_test.go
server/server_test.go
services/replay/service.go
tick/cmd/tickdoc/main.go

Fix of the Kapacitor crash on windows during recording: issues #902, #916. Verified on Windows 10 and Ubuntu 17.04
I would mark issue #902 as duplicate of #916 (#916 has more comments)  and update summary of #916 to  Crash of Kapacitor on Windows x64 when starting a recording
I've also fixed server tests to be platform independent.
Recording tests sometimes fail on deletion, server most probably slowly closes handles, I didn't dig into this.

Fix of the Kapacitor crash on windows when starting recording: issues #902, #916

---

cmd/kapacitord/main.go
cmd/kapacitord/run/command.go
services/diagnostic/service.go

Previously if an error was encountered with `cmd.Run`, the diagnostic would be nil and so when `m.Diag.Error` was called it would panic.
This PR now returns an error to the main function.

Bootstrap main diagnostic

---

CHANGELOG.md
alert.go
http_post.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/http_post.go
services/diagnostic/handlers.go
services/httppost/service.go

Add support for http status code as a field

---

CHANGELOG.md
integrations/streamer_test.go
server/server_test.go
services/snmptrap/service.go

Updated snmptrap service to fix https://github.com/influxdata/kapacitor/issues/1541

sysUpTime addition to snmptrap

---

CHANGELOG.md
server/server_test.go
task_master.go

Fixes https://github.com/influxdata/kapacitor/issues/1547
TODO:

Fix panic with replaying a recording

---

examples/nodes/tasks/alert.tick
examples/nodes/tasks/batch.tick
examples/nodes/tasks/combine.tick
examples/nodes/tasks/default.tick
examples/nodes/tasks/delete.tick
examples/nodes/tasks/eval.tick
examples/nodes/tasks/flatten.tick
examples/nodes/tasks/groupby.tick
examples/nodes/tasks/handle_loopback.tick
examples/nodes/tasks/httpout.tick
examples/nodes/tasks/httppost.tick
examples/nodes/tasks/influxdbout.tick
examples/nodes/tasks/join.tick
examples/nodes/tasks/log.tick
examples/nodes/tasks/loopback.tick
examples/nodes/tasks/sample.tick
examples/nodes/tasks/shift.tick
examples/nodes/tasks/statecount.tick
examples/nodes/tasks/stateduration.tick
examples/nodes/tasks/stats.tick
examples/nodes/tasks/stream.tick
examples/nodes/tasks/union.tick
examples/nodes/tasks/where.tick
examples/nodes/tasks/window.tick

This PR adds simple tickscripts for each node type in kapacitor and will serve as the basis for a burn-in test.

Add example of all nodes in load tasks style dir

---

CHANGELOG.md
services/k8s/client/client.go

Fixed [#1623](https://github.com/influxdata/kapacitor/issues/1623) regarding k8s in-cluster configuration setup and the dns resolution issue to master api server.

K8s incluster api addr fix

---

CONTRIBUTING.md

fixed the `git clone` command to include `.git` extension.

added .git extension to the git clone command

---

CHANGELOG.md
integrations/data/TestStream_EvalNow.srpl
integrations/data/TestStream_LambdaNow.srpl
integrations/streamer_test.go
tick/stateful/functions.go

This pull request adds a stateless function now() that could be used in conjunction with the recently merged function unixNano() to compare fields containing time encoded in nanoseconds with the current time.
Relevant feature request: [Add stateless function now() to get the current local time](https://github.com/influxdata/kapacitor/issues/1549)
(pull request beginner here, please let me know if I've made a mistake in the process, thanks)

Add now built in function

---

CHANGELOG.md
cmd/kapacitord/run/command.go
cmd/kapacitord/run/command_test.go

Remove the pidfile after the server has exited

---

CHANGELOG.md
services/diagnostic/api.go

Fixes #1641 
Writing headers is handled by the chunked HTTP response writer. Writing
headers manually results in an HTTP error log.

Stop writing HTTP header for sessions service.

---

pipeline/json.go
tick/ast/json.go
tick/ast/node.go

Found some bugs while testing various autogenerated tickscripts from chronograf.

Fixes to handle Pipeline/AST alert nodes and number types

---

cmd/kapacitord/run/command_test.go

Do not enable reporting on pidfile test, helps with timeout errors

---

tick/ast/json.go

Lists were incorrectly being unmarshaled into a map

Fix unmarshaling of AST node lists

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
server/server_test.go
services/victorops/config.go
services/victorops/service.go
services/victorops/victoropstest/victoropstest.go

Fixes #1250
In order to enable using JSON data add `json-data = true` to the `[victorops]` configuration section.

Fix VictorOps data being a string

---

pipeline/tick/swarm_autoscale.go
pipeline/tick/swarm_autoscale_test.go

Fix a typo in swarm_autoscale pipeline test

---

CHANGELOG.md
barrier.go
edge/grouped.go
edge/messages.go
integrations/streamer_test.go
pipeline/barrier.go
pipeline/node.go
pipeline/tick/ast.go
pipeline/tick/barrier.go
pipeline/tick/barrier_test.go
pipeline/window.go
task.go
window.go

Adding a BarrierNode to emit a BarrierMessage on intervals that are driven by the clock rather than by message timestamps.
Addresses portion of #1304 wherein "silent periods" need to be handled by minimum throughput detection pipelines.

Add BarrierNode to emit BarrierMessage periodically

---

CHANGELOG.md
server/server_test.go
services/mqtt/config.go

Previously, the `NewClientF` being exported was causing the our toml
package to panic.
Fixes https://github.com/influxdata/kapacitor/issues/1697

Fix panic with MQTT toml configuration generation

---

pipeline/tick/alert.go
pipeline/tick/alert_test.go

Found out that:
`tcp().address('echo:7')` doesn't work...
... and needs to be 
`tcp('echo:7')`

Update the TCP unmarshaling, putting address as node argument

---

pipeline/barrier.go
pipeline/barrier_test.go

This was missed in a recent merge.

Add JSON marshalling support to barrier node

---

CHANGELOG.md
barrier.go
integrations/streamer_test.go

addresses #1710
By having barrier time be based on last (point | barrier) time + idle,
the desired behavior of idle barrier for handling no data (silence)
scenarios works even when the data source clock is offset from the
kapacitor host clock.

make idle barrier time relative to messages

---

CHANGELOG.md
server/config.go
server/server_helper_test.go
services/httppost/config.go
services/mqtt/config.go

Previously `kapacitord config` generated TOML that looked like
```toml
httppost = []
mtqq = []
...
```
rather than
```toml
[[httppost]]
...
[[mqtt]]
...
```
this was due to `server.NewConfig` returning an empty slice of `Config`s
for httppost and mqtt.

Fix oddly generated TOML for mqtt & httppost

---

cmd/kapacitord/run/command.go
etc/kapacitor/kapacitor.conf

The `WARN` log level was not being used and removed in the process of adding the logging API features in Kapacitor 1.4.0. Note that it is still possible to set warn thresholds on alert nodes, this only affects Kapacitor internal logging.

Remove reference to WARN log level

---

CONTRIBUTING.md

This PR simply just changes the `package` flag to the correct one in CONTRIBUTING.md as seen in
https://github.com/influxdata/kapacitor/blob/master/build.py#L987

Fix package flag in CONTRIBUTING.md

---

pipeline/tick/alert.go
pipeline/tick/alert_test.go
pipeline/tick/combine_test.go
pipeline/tick/eval_test.go
pipeline/tick/from_test.go
pipeline/tick/function.go
pipeline/tick/group_by_test.go
pipeline/tick/http_post_test.go
pipeline/tick/influx.go
pipeline/tick/influx_test.go
pipeline/tick/k8s_autoscale_test.go
pipeline/tick/tick_test.go
pipeline/tick/udf_test.go

Several of the generated tickscripts had issues with
1. case (pushover's `uRL` and `uRLTitle`
2. removing nodes when arguments were incorrectly empty string (post, log, tcp, exec)
3. bottom/top were incorrectly generated as the field is the second argument
4. several tests generated incorrect tickscripts.  This had no functional problem, but, we don't want them as examples.

Fix various AST to tickscript issues found by more extensive testing

---

CHANGELOG.md
services/task_store/util.go

Fix deadlock in load service if task has error

---

CHANGELOG.md
alert.go
alert/types.go
integrations/batcher_test.go
integrations/streamer_test.go
server/server_test.go

Add Recoverable field to alert JSON response

---

CHANGELOG.md
change_detect.go
integrations/batcher_test.go
integrations/streamer_test.go
integrations/testdata/TestBatch_ChangeDetect.0.brpl
integrations/testdata/TestStream_ChangeDetect.srpl
pipeline/change_detect.go
pipeline/json.go
pipeline/node.go
pipeline/tick/ast.go
pipeline/tick/change_detect.go
pipeline/tick/change_detect_test.go
task.go

Node to detect changes between consecutive values in a series field

---

CHANGELOG.md
CONTRIBUTING.md
alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
pipeline/alert_test.go
pipeline/json_test.go
pipeline/tick/alert.go
pipeline/tick/alert_test.go
server/config.go
server/server.go
server/server_test.go
services/alert/service.go
services/diagnostic/handlers.go
services/diagnostic/service.go
services/pagerduty2/config.go
services/pagerduty2/pagerduty2test/pagerduty2test.go
services/pagerduty2/service.go
task_master.go

The PagerDuty API has stepped to v2 and it's a pretty serious refactor of the endpoint. While the v1 endpoint is still supported for some time, it's in deprecated mode and will ultimately be replaced soon(ish).
https://v2.developer.pagerduty.com/docs/events-api-v2
https://v2.developer.pagerduty.com/docs/getting-started

Support PagerDuty API v2

---

.circleci/config.yml

This is a feature of CircleCI that we are currently demoing. Should speed up docker image building.
https://circleci.com/docs/2.0/docker-layer-caching/

Enable docker layer caching in CircleCI

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
server/server_test.go
services/pagerduty2/config.go
services/pagerduty2/service.go

* Adds logic to understand pagerduty error response in full.
* Renames confusing test option.
* Renames ServiceKey to RoutingKey to match v2 API name.

Fix pagerduty2 integration

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
server/config.go
services/kafka/config.go

- Kafka was not being returned among the sections of the config in Kapacitor 1.5 out of the box.
- Two of the default Kafka config's duration values were missing quotes and caused errors when used as-is.
- Add a function to Kafka config to generate a new config, and make sure server generates that new config on startup.
- Properly quote the two durations in the default Kafka config.

Fix Kafka configuration

---

CHANGELOG.md
integrations/streamer_test.go
pipeline/alert.go
services/kafka/config.go
services/kafka/service.go

With this change the Async mode is used to write messages to Kafka. This mode allows for greater throughput at the cost of not blocking on the acknowledgment of the  writes. As such new statistics are added for each configured kafka cluster and topic. 
* write_errors - Reports the number of errors writing to Kafka for a given topic and cluster.
* write_messages - Reports the number of messages written to Kafka for a given topic and cluster.

Improve Kafka alert throughput

---

CHANGELOG.md
barrier.go
edge/consumer.go
pipeline/barrier.go
pipeline/barrier_test.go
pipeline/tick/barrier.go
pipeline/tick/barrier_test.go

Fixes #1157 
It is now possible to use the barrier node to delete/expire old groupds.

 Add delete support to barrier node 

---

CHANGELOG.md
client/v1/client.go
http/transport.go
influxdb/client.go
services/alerta/service.go
services/httppost/service.go
services/influxdb/service.go
services/k8s/client/client.go
services/slack/service.go
services/swarm/client/client.go

The http transport used in most places did not have sane defaults. This change consolidates creation of a new http transport. 
These changes only effect outgoing HTTP connections from Kapacitor, which tend to be low volume.

fix(http): use default transport consitently

---

barrier.go

Modified two different parts of the barrier node to prevent any
deadlocks. There were two possible methods to deadlock with one of these
found to be hit by people using these nodes.
The first was when a point was received, `Point` would be called and a
message would be sent to reset the timer. If the message queue was
backed up, then it was possible for `emitBarrier` to be called and for
it to try and forward a message to itself. But, the goroutine that was
reading the points from the edge was attempting to reset the timer so
the delete group message was never able to be consumed and the timer was
never able to be reset.
This first one was fixed by adding a buffer of size one to that channel
and making the reset non-blocking when the channel was full. This
guarantees that the message will …

fix: eliminate deadlocks in the barrier node when delete is used

---

CHANGELOG.md
build.py
scripts/post-install.sh

This PR makes rpm create files and directories with the right owner (user and group).  
This makes it possible to avoid changing ownership after install and so breaking verification (`rpm -V ...`).

fix(package): set rpm user and group to create files with correct owner

---

CHANGELOG.md
edge/stats.go

The delete messages were not honored in the Stats edge implementation. As such high cardinality tasks would collect stats on groups indefinitely. 
With this change the stats edge checks for delete messages and deletes its stats for the deleted group.

fix(edge): delete group stats when a group is deleted

---

CHANGELOG.md
models/point.go

This change avoids the allocation to build the GroupID, as this is a hot code path this optimization can greatly reduce total allocation thus reducing pressure on garbage collection.

avoid allocation when building group ID

---

build.py
scripts/post-install.sh
scripts/pre-install.sh

This also sets ownership change only on Debian-based systems (Amazon images are RH-based).

fix(package): create kapacitor user before install

---

CHANGELOG.md
etc/kapacitor/kapacitor.conf
integrations/helpers_test.go
server/config.go
server/server.go
services/httpd/service.go
tlsconfig/config.go

Fixes https://github.com/influxdata/kapacitor/issues/2193
This PR ports the TLS configuration functionality from https://github.com/influxdata/influxdb/pull/10150 to Kapacitor.
A new `[tls]` section is added to the configuration that allows a user to set:
- Which cipher suites to use
- A minimum supported TLS version
- A maximum supported TLS version
The TLS configuration is only wired up to the HTTP service in this PR.

Add TLS configuration options

---

influxql.gen.go
influxql.gen.go.tmpl
influxql.go

When the `AggregatePoint` method failed to convert the point to the
proper type, an error would happen and the underlying influxql code
would never receive the point within the aggregator.
But, the batch size would be incremented because the error was swallowed
instead of being reported back to the task node. This meant the task
believed that at least one point had been aggregated and it would
attempt to emit a point from aggregators that could not emit without at
least one point.
This change fixes the task so that it reports the error when it happens
instead of swallowing the error. This way, the error doesn't hide itself
with little evidence.
This has also been changed so the batch size is only incremented when an
error doesn't happen. The code had a path flow of incrementing the batch …

fix: return an error when aggregating a point fails

---

CHANGELOG.md
alert.go
server/server_test.go
services/alert/service.go
services/mqtt/service.go
task_master.go

This adds the ability to use templates when specifying the MQTT
topic. This is much more useful than static topics since you
can create topics like this:
switches/{{ index .Tags "agent_host" }}/ports/{{ index .Tags "port_num" }}

Add templating for MQTT topics

---

build.py

This change makes it so the build script no longer removes the release
version from the package version file names.

build(release): do not remove the release from the file name

---

udf/agent/README.md

Resolves #2069

---

Gopkg.lock
services/kafka/config.go
services/kafka/service.go
vendor/github.com/segmentio/kafka-go/batch.go
vendor/github.com/segmentio/kafka-go/conn.go
vendor/github.com/segmentio/kafka-go/consumergroup.go
vendor/github.com/segmentio/kafka-go/createtopics.go
vendor/github.com/segmentio/kafka-go/deletetopics.go
vendor/github.com/segmentio/kafka-go/error.go
vendor/github.com/segmentio/kafka-go/listgroups.go
vendor/github.com/segmentio/kafka-go/logger.go
vendor/github.com/segmentio/kafka-go/message.go
vendor/github.com/segmentio/kafka-go/metadata.go
vendor/github.com/segmentio/kafka-go/protocol.go
vendor/github.com/segmentio/kafka-go/reader.go
vendor/github.com/segmentio/kafka-go/recordbatch.go
vendor/github.com/segmentio/kafka-go/write.go
vendor/github.com/segmentio/kafka-go/writer.go

Errors on sending to kafka when they failed, used to fail silently. This
lead to user frustration.  This updates the kafka client and injects a
logger so they now fail loudly.

fix(kafka): update kafka lib; make kafka errors unsilent

---

CHANGELOG.md

I screwed up and didn't cut the changelog before releasing 1.5.5, this is the changelog for 1.5.5

chore: update changelog for 1.5.5

---

CHANGELOG.md
tlsconfig/config.go

Add TLS1.3 support

---

scripts/post-install.sh
scripts/post-uninstall.sh

Amazon Linux 2 uses systemd. This PR adds support for Amazon Linux 2 in `kapacitord`'s `post-install.sh` and `post-uninstall.sh` scripts.

Use Systemd for Amazon Linux 2

---

build.py

Currently arm64 aka aarch64 results in armhf binaries. Not ARM64 binaries. 
Modern arm chips (like those in TV boxes) does not support armhf instruction set.  exec format error.
The first change will detect aarch64 and set arch to arm64, which is supported.
Cleaned up code  around line 540 to store arch in fullarch for later use in if statement below that sets GOARM. Line 543 would overwrite the value tested in the if statement in 546 and down.
According to this: https://github.com/golang/go/wiki/GoArm GOARM should not be used for arm64

Update build.py to support arm64

---

.hooks/pre-commit
CHANGELOG.md

Go has deprecated invoking the `vet` tool through the `go tool` command, which flags an error in the pre-commit hook. This is a slight correction to use the `go vet` invocation instead.

Pre-commit hook `go vet` correction

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/alert_test.go
pipeline/json_test.go
pipeline/tick/alert_test.go
server/config.go
server/server.go
server/server_test.go
services/alert/service.go
services/diagnostic/handlers.go
services/diagnostic/service.go
services/discord/config.go
services/discord/discordtest/discordtest.go
services/discord/service.go
task_master.go

Added a [Discord Channel Webhook](https://discordapp.com/developers/docs/resources/webhook#execute-webhook) alert handler.

Feature: Discord Webhook Alert Handler

---

CHANGELOG.md
services/azure/service.go
services/consul/service.go
services/dns/service.go
services/ec2/service.go
services/file_discovery/service.go
services/gce/service.go
services/k8s/service.go
services/marathon/service.go
services/nerve/service.go
services/scraper/config_test.go
services/scraper/service.go
services/serverset/service.go
services/static_discovery/service.go
services/triton/service.go

The LAST one will be registered multi-times.
See [Range Gotcha](https://github.com/golang/go/wiki/Range#gotchas) :)

fix: multi same-type discovery configs

---

barrier.go
batch.go
pipeline/json.go
pipeline/json_test.go
stats.go

Closes https://github.com/influxdata/kapacitor/issues/2281

fix: panic when setting a zero interval for ticker

---

eval.go
integrations/streamer_test.go
integrations/testdata/TestStream_EvalDivisionByZero.srpl
tick/stateful/expr.go
tick/stateful/expr_dynamic_test.go

recovers and errors from other panics in lambdas
closes #2329

fix: error instead of panic on int div-by-zero

---

CHANGELOG.md
alert.go
pipeline/alert.go
services/pushover/service.go

Fix #2358 - Kapacitor ignoring the pushover().userKey() TICKScript operation [All Checks/Tests pass]

---

.circleci/config.yml
CHANGELOG.md
Gopkg.lock
Gopkg.toml
alert.go
pipeline/alert.go
services/pushover/service.go
vendor/github.com/gorhill/cronexpr/cronexpr_parse.go

upgrade github.com/gorhill/cronexpr lib

---

alert.go
http_post.go
integrations/batcher_test.go
integrations/streamer_test.go
integrations/testdata/TestStream_HttpPost_URL_Template.srpl
server/server_test.go
services/alert/service.go
services/httppost/config.go
services/httppost/service.go
task_master.go

This adds templating to the url for httpPost.

feat: httpPost url templating

---

CHANGELOG.md
alert/types.go
integrations/streamer_test.go

This adds .Details to AlertTemplates, where it should have been.

fix: .Details should be avaliable inside AlertTemplates

---

CHANGELOG.md
alert.go
pipeline/alert.go
server/server_test.go
services/opsgenie2/config.go
services/opsgenie2/service.go

Allows the addition of the _.RecoveryAction(...)_ method to the chain of the opsGenie2 service. Historically the recovery action was either _close_|_notes_ set in the global config which didn't allow uses cases where specific scripts wanted to deviate from the default behavior.
RFC: I'm not sure I fully grokked the model and pattern for config in kapacitor so would be good to make get some input on this.
TBC: Update documentation

RFC: Feature. Allow for overriding OpsGenieV2's alert recovery action

---

README.md

- Getting started has moved to `https://docs.influxdata.com/kapacitor/latest/introduction/getting-started/`
- More examples have already been removed from the [documentation](https://docs.influxdata.com/kapacitor/latest/examples/).

Fix 404 link on README.md

---

integrations/streamer_test.go
server/server_test.go

Fixes #2424.
Go 1.15 doesn't allow nil values for the 1st arg to context.WithValue.

test: use non-nil parent context in tests to avoid panics

---

alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
pipeline/tick/alert.go
server/server_test.go
services/servicenow/config.go
services/servicenow/service.go
services/servicenow/servicenowtest/servicenowtest.go

Closes #2428 
Implements [#202](https://github.com/influxdata/feature-requests/issues/202)
* changes _ServiceNow_ event handler to use _ServiceNow_ Event API instead of Table API.
Default value of ServiceNow URL has changed:
```
[servicenow]
enabled = false
url = "https://instance.service-now.com/api/global/em/jsonv2"
...
```
* adds support for `additional_info` elements in Event structure as requsted in FR [#202](https://github.com/influxdata/feature-requests/issues/202):
1. new handler property is introduced
| handler option | event field |
| --- |  --- |
| `additionalInfo` | entry in `additional_info` map |
2. `additional_info` is  a key-value pairs map and allows user to specify multiple entries. String values can be templates.
TICKscript example:
```
stream
|from() …
```

fix(servicenow): use recommended event API

---

etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
server/server_test.go
services/opsgenie2/config.go
services/opsgenie2/service.go

This is a _breaking_ change in the OpsGenie plugin behaviour of Kapacitor. The modification will use alert/event state details as description when opening OpsGenie alerts instead. This allows much more descriptive alerts in OpsGenie. Alert details in OpsGenie are still filled with the same key/values as before.
The current behaviour of simply encoding the event details as description is imho not very useful as a value for an OpsGenie alert description, Kapacitor alert details can provide much more information and are more in line with OpsGenie alert descriptions.
Would such a change make sense, or is it too breaking in current behaviour?

use kapacitor alert details as opsgenie description text

---

scripts/kapacitor.service

Previously you can not use service reload `systemctl reload  kapacitor` as ExecReload was skipped

Systemd ability to reload kapacitor configuration

---

CHANGELOG.md
services/alert/dao.go
services/alert/handlers.go
services/alert/handlers_test.go
services/alert/service.go

the topic handler match function `duration()` was colliding with the lambda function type conversion function `duration`.  This removes that collision by changing the name of the topic handler match function to `alertDuration`.

fix: topic-handler duration() -> alertDuration()

---

alert.go
pipeline/alert.go
services/bigpanda/config.go
services/bigpanda/service.go

This PR improves BigPanda alerting:
-  by default BP Alert contains all field values and tags
-  BigPanda primary and secondary property is configurable in tick script or in topic handler
```tick
alert
.bigPanda()
.appKey('fc39458f98e91eb0310258c3b725d643')
.primaryProperty('device')
.secondaryProperty('sensor_name')
.topic('bigpanda-topic')
```
or in topic hadler
```yaml
id: bigpanda-cpu-alert
topic: bigpanda-topic
kind: bigpanda
options:
app-key: '8f5795cada387b9f310f41fc369c88e4'
primary-property: 'host'
secondary-property: 'check'
url: 'http://localhost:8080/data/v2/alerts'
```

feat: add fields to BigPanda alert

---

CHANGELOG.md
influxdb/client.go
influxdb/client_test.go
influxdb/gzip.go
services/influxdb/config.go

This gzips data by default that is sent to influxdb.

Gzip data by default that is sent to influxdb.

---

.circleci/config.yml
CHANGELOG.md
Dockerfile_build_ubuntu32
build.py
test.sh

Go no longer supports darwin 386 support, so we must remove 386 darwin support.
We also added darwin arm64 support.

chore: remove 386 darwin support and add arm64 darwin

---

services/pagerduty2/service.go

Pagerduty made Ruleset feature (https://support.pagerduty.com/docs/rulesets) available to everyone couple of months back.
The issue is that `trigger` and `resolve` events need to be routed to the same service when rulesets are used.
Because the resolve event only contains a subset of the trigger payload, it's very complicated to do proper routing.
Pagerduty is accepting the full payload on resolve just fine (I tested it with our infrastructure) and the extra keys in the payload allows proper routing.

[pagerduty] send full event payload on resolve

---

edge/consumer.go
flatten.go
group_by.go
integrations/helpers_test.go

This adds barrier handling to flatten, so that barriers actually cause flatten to emit its points.
Unfortunately, because of the timing stuff here, its quite hard to test this in an automated way.  I've tested it manually, and will think about how to test these in a more automated way with the PR for join's barrier handling.

fix: add barrier handling to flatten

---

pipeline/tick/alert.go

Fixes generated function node name for _ServiceNow_ event handler.

fix: function node name for ServiceNow handler

---

pipeline/tick/alert.go
pipeline/tick/alert_test.go

This PR Fixes TickScript AST processing so that it includes BigPanda alert handler.
Additionally, it also adds a test for `serviceNow` alert handler AST parsing.

fix(bigPanda): add TICKscript AST processing

---

services/kafka/service.go
services/kafka/service_test.go

fix: avoid infinite hang when closing Kakfa writer

---

alert.go
etc/kapacitor/kapacitor.conf
integrations/streamer_test.go
pipeline/alert.go
pipeline/alert_test.go
pipeline/json_test.go
pipeline/tick/alert.go
server/config.go
server/server.go
server/server_test.go
services/alert/service.go
services/diagnostic/handlers.go
services/diagnostic/service.go
services/zenoss/config.go
services/zenoss/service.go
services/zenoss/zenosstest/zenosstest.go
task_master.go

This PR adds _Zenoss_ event handler as requested by https://github.com/influxdata/feature-requests/issues/72. Fixes https://github.com/influxdata/kapacitor/issues/2483.
The handler provides options for Zenoss [basic event fields](https://help.zenoss.com/zsd/RM/administering-resource-manager/event-management/event-fields):
| handler option | event field | default value |
| --- |  --- | --- |
| `summary` | Summary |  `'{{ .Message }}'` |
| `device` | Device | "" (empty string) |
| `component` | Component | "" (empty string) |
| `severity` | Severity | severity level (see Severity mapping) |
| `eventClass` | Event Class |  "" (empty string) |
| `eventClassKey` | Event Class Key | "" (empty string) |
| `collector` | Collector (optional) | _none_ |
| `message` | Message (optional) | _none_ | …

feat: Zenoss event handler

---

CHANGELOG.md
client/API.md
client/v1/client.go
client/v1/client_test.go
go.mod
server/config.go
server/server.go
server/server_helper_test.go
server/server_test.go
services/alert/dao_easyjson.go
services/auth/cache.go
services/auth/config.go
services/auth/dao.go
services/auth/meta/client.go
services/auth/meta/errors.go
services/auth/meta/types.go
services/auth/service.go
services/auth/service_internal_test.go
services/auth/service_test.go
services/bigpanda/config.go
services/bigpanda/service.go
services/diagnostic/handlers.go
services/diagnostic/service.go
services/storage/version_easyjson.go

Closes https://github.com/influxdata/kapacitor/issues/2505
And add a config option to enable it.

feat: pull in auth code from Kapacitor Enterprise

---

services/sideload/service.go
services/sideload/service_test.go

closes https://github.com/influxdata/kapacitor/issues/2527

fix: race in sideload update

---

pipeline/tick/alert.go
pipeline/tick/alert_test.go

This PR Fixes TickScript AST processing so that it includes Teams alert handler. This is required in order to fully support Teams alert configuration in Chronograf ( influxdata/chronograf#5732 )

fix(teams): add TICKscript AST processing

---

.gitignore
pipeline/alert.go
server/server_test.go
services/teams/service.go

This PR fixes Teams alert handler to always serialize ChannelURL to `channel-url` JSON property. Before this PR, `channel-url` was used in the global configuration and `channel_url` in a specific handler configuration and for handler testing. Different names are causing problems in influxdata/chronograf#5740, which naturally expects the same property name when overriding the configured default per alert instance.
Additionally, it adds golang's `vendor` directory `.gitignore`

fix(teams): make ChannelURL naming consistent

---

alert.go
pipeline/alert.go
pipeline/tick/alert.go

Changes Zenoss property name to camel case, uppercase seems to break Kapacitor integration.

fix: Zenoss property name compatibility

---

server/server_test.go
services/bigpanda/service.go

Closes influxdata/chronograf#5753
This PR fixes BigPanda service so that its testing functionality
- uses the configured AppKey (it was fake before this PR)
- uses current time timestamp (it was 0 since epoch before this PR)

fix(bigpanda): setup test options from configuration

---

CHANGELOG.md
integrations/streamer_test.go
server/server_test.go
services/slack/config.go
services/slack/service.go
services/slack/slacktest/slacktest.go

feat: enable new-style slack apps

---

pipeline/alert.go
server/server_test.go
services/teams/service.go

This PR reverts consistent ChannelURL JSON mapping introduced in #2545, it would cause anyone who has Teams Pipeline saved to lose that field from their pipeline. 
In order to preserve backward compatibility, MS Teams ChannelURL has to remain `channel_url` in TICKscript and `channel-url` in the config. This discrepancy requires an extra care in chronograf 1.9 that added Teams alert/configuration UI.

fix(teams): revert ChannelURL mapping to preserve BC with saved TICKscripts

---

cmd/kapacitor/fluxtask.go
cmd/kapacitor/main.go
services/httpd/handler.go

Closes #2578 
Before:
➜  ./kapacitor -url http://steve:pas@localhost:9092 flux task list
undefined response type
➜  ./kapacitor -url http://steve:pass@localhost:9092 flux task list
undefined response type 
After:
➜  ./kapacitor -url http://steve:pas@localhost:9092 flux task list
Error: authorization failed
➜  ./kapacitor -url http://steve:pass@localhost:9092 flux task list
ID                      Name    Organization ID Organization    Status  Every   Cron
079625bc3aeb8000        poster                                  active  3s

fix: cli auth and error handling for flux tasks

---

barrier.go
edge/messages.go

Bug : 
```
ts=2021-06-14T07:27:50.277Z lvl=error msg="node failed" service=kapacitor task_master=main task=Infra-Kubernetes-ContainerCPUUsage node=barrier2 err="unexpected message of type *edge.deleteGroupMessage"
ts=2021-06-14T07:27:50.279Z lvl=error msg="node failed" service=kapacitor task_master=main task=Infra-Kubernetes-ContainerCPUUsage node=from1 err="edge aborted"
ts=2021-06-14T07:27:50.387Z lvl=error msg="node failed" service=kapacitor task_master=main task=Infra-Kubernetes-ContainerCPUUsage node=stream0 err="edge aborted"
```
RCA : `deleteGroupMessage` was not compliant with `GroupInfoer` interface
Fix : make `deleteGroupMessage` was compliant with `GroupInfoer` interface
Changelog: Commit
Signed-off-by: Prashanth Joseph Babu
_You can erase any checkboxes below this note if they …

make deleteGroupMessage align with GroupInfoer interface

---

CHANGELOG.md
services/bigpanda/service.go
services/bigpanda/service_test.go

Closes https://github.com/influxdata/EAR/issues/2365
This PR changes how are serialized `fields of alerting` data into BigPanda payload - use original type of field instead mapping a field value to `string`.

fix(bigpanda): fields of alerting data point are serialized to proper types

---

CHANGELOG.md

There was a typo in the position of a changelog item, this puts it in the right place,

Typo:changelog for merge, in wrong place

---

CHANGELOG.md
services/bigpanda/service.go
services/bigpanda/service_test.go

Related to https://github.com/influxdata/EAR/issues/2365
The `Additional attributes` of BigPanda alerts should be serialized as a `string`. See docs:
https://docs.bigpanda.io/reference#alerts

fix(bigpanda): fields of alerting data point should be serialized as a string

---

LICENSE_OF_DEPENDENCIES.md
go.mod
go.sum
influxdb/token_client.go
server/server_test.go
services/auth/meta/client.go
services/httpd/handler.go

This switches our jwt library because of a security bug in
github.com/dgrijalva/jwt-go

security: switch to github.com/golang-jwt/jwt

---

expvar/expvar.go

Fixes #2583 
RCA: The `String()` function of type `String` should perform a json.Marshal to ensure it generates a valid json even for special chars . 
Ref :  https://golang.org/src/expvar/expvar.go?s=5421:5453#L233
Changelog: Commit
Signed-off-by: Prashanth Joseph Babu <prashanthjbabu@gmail.com>

expvar string json encoding to handle special chars

---

CHANGELOG.md
client/v1/client_test.go
client/v1/swagger.yml
services/task_store/service.go

Closes #2619 
This PR adds template-id OOTB to the list of returned tasks. It includes also tests, an updated swagger file, and housekeeping of staticcheck errors on updated files.
Adding template-id to task list  helps chronograf with processing and visualization of templated tasks. Details are explained in  influxdata/chronograf#5807

feat(tasks): add template-id to task list

---

CHANGELOG.md
barrier.go
http_post.go
influxdb/client.go
influxdb/client_test.go
influxdb/token_client.go
services/auth/service.go
services/bigpanda/service_test.go
services/discord/service.go
services/fluxtask/service.go
services/httppost/service.go
services/influxdb/service.go
services/influxdb/service_test.go
services/load/service.go
services/smtp/service.go
services/teams/service.go
services/telegram/service.go
task/backend/analytical_storage.go
task/config.go
tick/stack.go

Closes #2620
Flux task logs are stored in the "Analytic Store", which is backed
by an influxdb 1.x Database or 2.x Bucket.
Auto-creation gives an infinite retention policy, which can be adjusted later by the user.
Note that for 1.x, "database/rp" bucket names will not be autocreated, only
bare "database" bucket names. This could potentially be added in the future
but the assumption is if a user wants control over the retention policy name
they probably want to control the retention policy creation as well.
Tested manually against 1.x and 2.x.

feat: auto-create 1.x DB or 2.x bucket for flux task logs

---

CHANGELOG.md
alert.go
integrations/streamer_test.go
pipeline/alert.go
pipeline/tick/alert.go
pipeline/tick/alert_test.go
server/server_test.go
services/alerta/alertatest/alertatest.go
services/alerta/service.go

Fix influxdata#2349
This commit adds support for custom Alerta alert attributes (see Alerta Alert Format for details).
Attributes are specified with "attribute" keyword in tick script, e.g.:
|alert()
// ...
.alerta()
// ...
.attribute('customUrl', 'https://example.com/')
.attribute('booleanAttribute', TRUE)
.attribute('numericAttribute', 9001)
.attribute('templatedAttribute', 'Templates are supported: {{ .Name }}')

feat(alerta-service): Support the "attributes" attribute in Alerta node

---

go.mod
pipeline/tick/tick_test.go

This removes the depreciated importer.For.  This removal allows tests to be module aware.

test(tick): remove depreciated importer.For

---

influxdb/event_parser.go

Flux is much more general purpose than tick script, and can handle data that isn't a time series.  However, Tick cannot understand this data.  When people output one of these scripts into a tick script, we error.  The error wasn't descriptive enough and was causing confusion.

fix: better error message for flux data without the appropriate columns

---

go.mod
server/config.go
server/config_test.go
server/parseenv.go

This allows for example: adding new headers to httpposts via
environmental variables

feat(config): Env var config can now add new items

---

alert/topics.go
integrations/streamer_test.go
server/server.go
services/alert/config.go
services/alert/service.go

This is a tuning param to make the topic queue length configurable.  This is useful if very large amounts of alerts must go off due to scheduled maintenance etc such as a windows update.

feat(topics): make topic queue length configurable

---

services/httpd/handler.go

This cleans up ingestion by getting rid of the `http.Request.FormValue` usages and switching to just looking at query params.
This shouldn't affect perf very much, as  `http.Request.FormValue` short circuits to query params if the right content types are not set. Still this is clearer and avoids quite a few calls.

perf(ingestion): switch from using formvalue to query params

---

build.py

It appears that `x86_64-apple-darwin16-clang` has been upgraded to `x86_64-apple-darwin18-clang` in our cross-compiler container. The cross-compiler did not provide a compatibility symlink, so `x86_64-apple-darwin16-clang` is no longer on that path.

build: upgrade darwin cross compiler

---

.circleci/config.yml
Dockerfile_build_ubuntu64

This fixes the following CVEs in go
CVE-2022-1705: net/http: improper sanitization of Transfer-Encoding header (medium)
CVE-2022-1962: go/parser: stack exhaustion in all Parse* functions (negligible)
CVE-2022-28131: encoding/xml: stack exhaustion in Decoder.Skip (medium)
CVE-2022-30630: io/fs: stack exhaustion in Glob (medium)
CVE-2022-30631: compress/gzip: stack exhaustion in Reader.Read (medium)
CVE-2022-30632: path/filepath: stack exhaustion in Glob (medium)
CVE-2022-30633: encoding/xml: stack exhaustion in Unmarshal (medium)
CVE-2022-30635: encoding/gob: stack exhaustion in Decoder.Decode (medium)
CVE-2022-32148: When httputil.ReverseProxy.ServeHTTP was called with a Request.Header map (low)

fix(security): update go to 1.18.4

---

.circleci/config.yml

Since the binaries/packages are being uploaded to `kapacitor/releases/nightly`, upload the changelog into the same directory.

chore: move changelog to "kapacitor/releases/nightly"

---

cmd/kapacitord/run/command_test.go
integrations/streamer_test.go
server/server_helper_test.go
server/server_test.go

A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
N/A, test changes only.
i.e., ("recommend to upgrade immediately", "upgrade at your leasure", etc.)
- Feat: a feature with user-visible …

test: use `T.TempDir` to create temporary test directory

---

.circleci/config.yml
Dockerfile_build_ubuntu64

This fixes the following CVEs in go:
* CVE-2022-32189 - encoding/gob & math/big: decoding big.Float and big.Rat can panic
* CVE-2022-27664 - net/http: handle server errors after sending GOAWAY
* CVE-2022-32190 - net/url: JoinPath does not strip relative path components in all circumstances

fix(security): update go to 1.18.6

---

.circleci/config.yml
Dockerfile_build_ubuntu64

Go 1.18.7 and 1.19.2 were released which fixes:
* CVE-2022-2879 - archive/tar: unbounded memory consumption when reading headers
* CVE-2022-2880 - net/http/httputil: ReverseProxy should not forward unparseable query parameters
* CVE-2022-41715 - regexp/syntax: limit memory used by parsing regexps.
None of these seem to actually affect kapacitor and so this PR isn't security relevant, but it would be nice to get it on the latest Go before the next kapacitor release.

chore: update go to 1.19.2

---

go.mod
go.sum

Performed:
```
$ go mod edit -require go.mongodb.org/mongo-driver@v1.5.1
$ go mod tidy
$ go test ./...
```
Note, `go test ./...` initially failed locally with:
```
--- FAIL: TestServer_UDFStreamAgents (0.66s)
server_test.go:5509: open service *udf.Service: failed to load process info for "movingAvg": exec: "python": executable file not found in $PATH
2022/11/21 11:08:32 Server listening on /tmp/TestServer_UDFStreamAgentsSocket84497654/001/mirror.go.sock
2022/11/21 11:08:32 Starting agent for connection 0
2022/11/21 11:08:32 Agent for connection 0 finished
2022/11/21 11:08:32 Starting agent for connection 1
2022/11/21 11:08:32 Agent for connection 1 finished
2022/11/21 11:14:45 Server stopped
--- FAIL: TestServer_UDFStreamAgents (0.66s)
server_test.go:5509: open service *udf.Service: …
```

chore: update go.mongodb.org/mongo-driver to 1.5.1 for dependabot

---

build.py

This fixes an issue in the release and nightly workflows where "aarch64-unknown-linux-musl-cc" cannot be found.

fix: specify correct aarch64 gcc path

---

task_master.go

The TaskMaster type has to implement WritePointsPrivileged instead of WritePoints because of the Influxdb reference update in go.mod from 1.8.4 to 1.9.6
closes https://github.com/influxdata/kapacitor/issues/2735

fix: make WritePointsPrivileged call WritePoints

---

.circleci/config.yml

This executes the "release" workflow when a tag ending in "test" is pushed. I pushed "BNP_taskstore-1-test" and it generated these: https://app.circleci.com/pipelines/github/influxdata/kapacitor/1622/workflows/c1ba3aef-b77d-48c6-85e2-d7e4910f212b/jobs/6981/artifacts

chore: build testing tags

---

integrations/history_clean_test.go
services/alert/service.go

Fixes bug in JSON lexer use in restoring topics from disk. Re-initialize the lexer after each EventState. 
Adds tests to verify correct close and restore operation with new history deletion on alert state reset 
to OK.
recommend to upgrade immediately
closes https://github.com/influxdata/kapacitor/issues/2723

fix: move struct initialization inside loop

---

etc/kapacitor/kapacitor.conf
go.mod
go.sum
integrations/metaauth_test.go
services/auth/config.go
services/auth/meta/client.go
services/auth/service.go

Add JWT meta API authentication using the new `[auth] meta-internal-shared-secret` configuration parameter.
Backport of #2754.
closes: #2755
(cherry picked from commit 025c7067e4f8732a0168135807ad065f4303dfe7)

feat: add JWT meta API authentication

---

.circleci/config.yml
Dockerfile_build_ubuntu64

https://github.com/influxdata/edge/issues/520

chore(build): upgrade Go to 1.20.10

---

.circleci/config.yml

Install `dotenv` gem dependency with locked at version `2.8.1` .
To fix CI build:
https://app.circleci.com/pipelines/github/influxdata/kapacitor/2132/workflows/2422dbee-a1cb-48e7-8605-abf3969d5bb2/jobs/8577
- Feat: a feature with user-visible changes
- Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
- Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
- Build: build script changes, CI config changes, build tool updates
- Refactor: non-user-visible refactoring
- Check the PR title: we should be able to put this as a one-liner in the release notes

build(ci): use compatible dependencies with Ruby v2

---

CHANGELOG.md

Update `CHANGELOG.md` for `1.7.2 GA`
We are ready to release `1.7.2 GA`.

chore: update CHANGELOG.md for 1.7.2 GA

---

server/migrate_topic_store_test.go
services/alert/migrate_topic_store.go

Closes [#4984](https://github.com/influxdata/EAR/issues/4984)

fix: do not migrate events with empty ID

---

CHANGELOG.md

Update `CHANGELOG.md` for `1.7.3 GA`
We are ready to release `1.7.3 GA`.

chore: update CHANGELOG.md for 1.7.3 GA

---

SECURITY.md

We don't require nor publish the GPG key for reporting security issues any more.

chore: tweak wording and don't reference gpg key in SECURITY.md

---

go.mod
go.sum

Closes https://github.com/influxdata/edge/issues/633

chore(deps): upgrade aws-sdk-go to v1.51.12

---

CHANGELOG.md

Update `CHANGELOG.md` for `1.7.4 GA`
We are ready to release `1.7.4 GA`.

chore: update CHANGELOG.md for 1.7.4 GA

---

CHANGELOG.md

Update `CHANGELOG.md` for `1.7.5 GA`
We are ready to release `1.7.5 GA`.

chore: update CHANGELOG.md for 1.7.5 GA

---

.circleci/config.yml

This PR addresses issues in the CI steps that utilize the `aws` command. The `ubuntu:latest` image does not include `awscli` in its default repositories, necessitating a switch to the `debian:latest` image for these operations.
This approach aligns with strategies used in other projects, such as `influxctl`. For reference, see how `influxctl` configures its CI environment: [influxctl CI configuration](https://github.com/influxdata/influxctl/blob/6121cedc1e19508ad2e2a6dfc00a69d3b0d48a2f/.circleci/config.yml#L160).
https://app.circleci.com/pipelines/github/influxdata/kapacitor/2295/workflows/ccd091f8-98b5-4ac1-a23b-73fb54717193/jobs/9093

fix(ci): use debian image for `aws` commands

---

.circleci/config.yml
Dockerfile_build_ubuntu64
builder/Dockerfile_build
builder/Dockerfile_build_push.sh
builder/README.md
builder/fs/root/.cargo/config
builder/fs/usr/local/bin/build-version.sh
builder/fs/usr/local/bin/pkg-config.sh
builder/fs/usr/local/bin/xcc
builder/fs/usr/local/src/musl-gcc/musl-gcc.specs.sh.patch

This PR add missing builders toolchain to our custom builder.

feat: add missing deps for crossbuilder

---

alert.go
server/server_test.go
services/storage/storagetest/storage.go

Forcing batch alert time timezone to UTC. Fixes #938 and  [EAR #5376](https://github.com/influxdata/EAR/issues/5376)
Stream alert also has the time in the UTC zone.
The `.Time` variable printed as a string will always be in UTC.
- Feat: a feature with user-visible changes
- Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
- Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
- Build: build script changes, CI config changes, build tool updates
- Refactor: non-user-visible refactoring
- Check the PR title: we should be able to put this as a one-liner in the release notes

fix: using UTC timezone for alert levels

---

.circleci/config.yml
Dockerfile_build_ubuntu64
builder/Dockerfile_build
go.mod

Closes https://github.com/influxdata/edge/issues/748

chore(build): upgrade Go to 1.22.7

---

etc/kapacitor/kapacitor.conf
go.mod
go.sum
services/kafka/config.go
services/kafka/sasl.go
services/kafka/sasl_test.go
services/kafka/service.go
services/kafka/token.go

Adding SASL OAUTH token refreshing for Kafka plugin. The same support as Telegraf has - custom, Auth0, AzureAD.
Kapacitor docs update PR: [#5617](https://github.com/influxdata/docs-v2/pull/5617)
New Kafka config params:
- sasl-oauth-service
- sasl-oauth-client-id
- sasl-oauth-client-secret
- sasl-oauth-token-url
- sasl-oauth-token-expiry-margin
- [kafka.sasl-oauth-parameters]
- sasl-oauth-tenant-id
- sasl-oauth-scopes

feat: Kafka SASL OAUTH token refreshing

---

CHANGELOG.md

Update `CHANGELOG.md` for `1.7.6 GA`
We are ready to release `1.7.6 GA`.

chore: update CHANGELOG.md for 1.7.6 GA

---

.circleci/config.yml
Dockerfile_build_ubuntu64
builder/Dockerfile_build

- [n/a] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium)
- [n/a] openapi swagger.yml updated (if modified API) - link openapi PR
Upgrades reference go release to go1.22.12.  
It is best to keep product up to date with latest releases.  Since we cannot yet upgrade to go1.23 because of old protobuf dependencies in user defined functions (UDF), which might break customer implementations, at least we can upgrade to the latest release of go.12.12
Affects primarily the build
- Feat: a feature with user-visible changes
- Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
- Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must …

chore: upgrade reference go version to go1.22.12

---

CHANGELOG.md
go.mod
influxdb/token_client.go
integrations/metaauth_test.go
server/server_test.go
services/auth/meta/client.go
services/httpd/handler.go

- [n/a] Sample config files updated (both `/etc` folder and `NewDemoConfig` methods) (influxdb and plutonium)
- [ n/a] openapi swagger.yml updated (if modified API) - link openapi PR
Upgrades golang-jwt to use newer version v4.
Improves security by using a more up-to-date version of the library, in keeping with the `influxdb` project.  
No user visible changes.
- Feat: a feature with user-visible changes
- Fix: a bug fix that we might tell a user “upgrade to get this fix for your issue”
- Chore: version bumps, internal doc (e.g. README) changes, code comment updates, code formatting fixes… must not be user facing (except dependency version changes)
- Build: build script changes, CI config changes, build tool updates
- Refactor: non-user-visible refactoring …

chore: upgrade golang-jwt to v4
